### ISSUE TITLE
Authentication lifetime could behave like a session

### ISSUE THREAD

**Issue by rmotitsuki** [kytos/kytos#1013]
The authenticated service could have a timeout that expires after the last service interaction.
Today, the timeout exists for the token created on the first service call.

**Comment by gleybersonandrade** [comment]
Related to #1128

**Comment by rmotitsuki** [comment]
In JWT implementation the timeout is encoded inside the token. To create a session-like communication, the server must update the token and send it back to the user. 
It is not possible to send the token for every REST call (GET, POST, PATCH, DELETE), and creating an token update call can create a security issue, with hijacked token and infinite token update. 
For now, the session feature will not be implemented.
