### ISSUE TITLE
Create controller restart action

### ISSUE THREAD

**Issue by macartur** [kytos/kytos#103]
Today the Kyco controller don't have a restart action.

**Comment by beraldoleal** [comment]
If we are talking about the `Controller` class methods, a basic implementation is straightforward. Please make sure to have this as command on `kytosd` command line. Please see #9

**Comment by diraol** [comment]
@beraldoleal What should be the behavior of this "restart"? A `shutdown` followed by the instantiation of a new "empty" `Controller` object (and it's `start`)?
There is any data that should be kept between both instances?

**Comment by beraldoleal** [comment]
@diraol yes, as you said.
