### ISSUE TITLE
Ensure persistence for kytos core and topology NApps

### ISSUE THREAD

**Issue by gleybersonandrade** [kytos/kytos#1040]
Today, if kytos fails, attributes of entities such as switch.enabled and interface.enabled will be reset. We need to find a way to ensure the persistence of this data.

**Comment by cmagnobarbosa** [comment]
Related https://github.com/kytos/of_lldp/issues/49

**Comment by cmagnobarbosa** [comment]
Related: kytos/kytos#1127
