### ISSUE TITLE
Create configuration only in post-install (or kytosd bootstrap)

### ISSUE THREAD

**Issue by hdiogenes** [kytos/kytos#1042]
Today Kytos tries to create its configuration at install time, a behavior that causes three problems for us:

* `SandboxViolation` when installing Kytos as a dependency from PyPI - #494
* Distribution only in source format (no wheel file) - #922
* "There is no config file." when starting `kytosd` - #951

That means we have to change the creation of configuration files to `post-install` or to the `kytosd` initialization so that we can close those three issues.

Older issues also related: #471 #385.

**Comment by josemauro** [comment]
Trying to implement this approach we are facing the following scenario once kytosd is executed:
It could be executed after develop mode install: using links to ETC_FILES and TEMPLATE_FILES. 
It could be executed after regular mode install: using a copy of ETC_FILES and TEMPLATE_FILES. 
If we are going to manage this steps after installation what is best way to control the steps above when starting kytosd? I mean, do we have to check if it is develop or regular installation in run time, right?
