### ISSUE TITLE
Consistency of flows checking

### ISSUE THREAD

**Issue by italovalcy** [kytos/kytos#1120]
Description: The orchestration tool should provide a routine to check the consistency between the flow tables on the switches and the orchestration tool's database. Thus, if an OpenFlow flow entry is missing in the switch's table (e.g., due to an error, accidental removal from the operator, or another (conflicting) tool managing the switch), the orchestration tool should reinstall the flow. The same applies if there are more (unknown) flows than what it should be (according to the database): they should be removed - with several exceptions. The admin defines the exception list, and this list should be a persistent configuration. This list of exceptions will avoid Kytos to remove "wanted" flows that are not related to any service provided by Kytos (e.g., the third party installed flows).

Expected deliverables:

- The admin should configure the list of exceptions. The exceptions can be based on cookies or match conditions. We need to check how the cookies are being used today on Kytos to decide. Anyway, it should support restrict exceptions definition, and it should also support some kind of regex/range
  - example 1: ignore rules with cookies== 0x2b00000000000011
  - example 2: ignore rules with cookies range 0x2b00000000000011 - 0x2b000000000000ff
  - example 3: ignore flows with VLAN-id 3333 [they were created by tool XYZ]
  - example 4: ignore flow in_port=10,ether_type=0x8344,vlan_vid=100
  - example 5: ignore all flows on OpenFlow table 3
- Every 30 seconds, the orchestration tool should check the consistency and add/remove/modify the flows on the switch's flow table according to the flow database + exceptions
- The inconsistencies fixed should be notified by logging or e-mail (via Notifications NApp)

**Comment by josemauro** [comment]
The support for list of exceptions in consistency system will be moved to issue https://github.com/kytos/kytos/issues/1221
