### ISSUE TITLE
Persistence of all input from users

### ISSUE THREAD

**Issue by italovalcy** [kytos/kytos#1127]
Description: all actions, configurations, and changes requested by the network operator should be saved to ensure the persistency of the system

Expected deliverables:
- All user input should be saved (all requests for GET/POST/PATCH/DELETE should be saved, etc.)
- Save before applying
- For means of audibility, the changes should be registered

**Comment by hdiogenes** [comment]
@italovalcy I think the 3rd point is a whole new feature and should be registered as such.
