### ISSUE TITLE
Shutdown API command error

### ISSUE THREAD

**Issue by dgarc330** [kytos/kytos#1227]
When I try to shutdown kytos via the API like so: http://67.17.206.252:8181/api/kytos/core/shutdown/

I get the following error:

Access to 67.17.206.252 was denied.
You don't have authorization to view this page.
HTTP ERROR 403

**Comment by cmagnobarbosa** [comment]
Hello @daniella, are you trying to shutdown an instance of Kytos running on another machine?

If you were running Kytos locally, you can try using http://127.0.0.1:8181/api/kytos/core/shutdown/ or http://localhost:8181/api/kytos/core/shutdown/

**Comment by dgarc330** [comment]
Hey there, I'm not trying to shutdown kytos locally. I'm trying to shutdown a kytos instance within a docker container in a remote machine. That is why I tried sending the request via the API but was faced with that error. Any ideas what is causing it or how to get around it? All the other endpoints I use are working fine except for that one

**Comment by cmagnobarbosa** [comment]
Checking the shutdown API code, this endpoint today, does not work properly when used on remote machines. The only host with permission to make the shutdown request is localhost. Therefore, for this command to work, you need to connect to the remote machine and make this request locally.

But we are already discussing the best way to overcome this limitation.

https://github.com/kytos/kytos/blob/master/kytos/core/api_server.py#L156~#L165

**Comment by josemauro** [comment]
Hello everyone, I think we reached a conclusion for this issue. First thing to
know is that the shutdown endpoint is not intended to be used via external 
access. After discussions between me, @hdiogenes , @italovalcy  and @rmotitsuki  
the conclusion is that this endpoint is available to make possible to shutdown the 
API server and not to shutdown Kytos. The PR #1249 is going to revert the changes that
was applied in #1231 following the demand that have arisen from this PR. Besides
that, the PR #1249 will propose better names and descriptions to avoid that
others reach the same misunderstanding that we and @dgarc330  had, i.e., the 
shutdown endpoint is intended to finish kytos.
