### ISSUE TITLE
Implement interactive console - CLI

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#13]

**Comment by diraol** [comment]
`begins` is a python library to help the development of CLI programs, I think it would be good for us to consider using it to make our code cleaner and easier to implement and extend.

Ref: https://pypi.python.org/pypi/begins/0.9

**Comment by erickvermot** [comment]
current CLI presents some issues:
I believe ``kytos -h`` info is outdated,
and ``kytos server`` commands do not seem to work...

**Comment by beraldoleal** [comment]
@erickvermot yes, `kytos server` is not working, yet.

Let 's not confuse `kytos` with `kytosd`. `kytos` should be updated since that is using `docopt`, if not, let's fix, but on `kytos-utils` repo.

`kytosd` should start using `docopt` as well. This interactive console issue is on `kytosd`, not on `kytos` client. Something like: `kytosd -i` should start kytos in foreground and in "interactive mode" (with a console). Also, `kytosd` should start in daemon mode, but open a socket or something that should be easy to client "kytos" to connect with in a interactive mode.

So we could have kytosd running on one server, and kytos client connecting from another machine.

**Comment by beraldoleal** [comment]
@diraol I was thinking something about native python console like ipython/jupter, that has already socket options (thinking on the future.. websockets).

But yes, for sure even using ipython we should define some basic commands. If I understood right, I think that begins is more for argparser, right ? (We already use docopt).

http://ipython.readthedocs.io/en/stable/interactive/tips.html#embed-ipython-in-your-programs
https://coderwall.com/p/w78iva/give-your-python-program-a-shell-with-the-cmd-module

**Comment by diraol** [comment]
@beraldoleal you are right, `begins` is more focused on CLI tools, like docopt. When I posted this issue I was thinking on a CLI, like our `kytos-utils` tool. But for an `interactive shell` It seems to me that going with ipython would be a good choice. May be would be good to do a small research about common/standard solutions like ipython/jupyter for an interactive shell.

**Comment by beraldoleal** [comment]
I just implemented a basic interactive console on last commit. Now running:

```
kytosd -f
```

It will redirect you to a console. I'm closing this and each individual new feature on this console we open a new issue.
