### ISSUE TITLE
Check possible memory leak on Kyco

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#134]
Kyco has been shutdown by the kernel twice, we need to find out what is going on.

Does it have something to do with our logging process? Are we saving the log somewhere in memory without the necessary care?

@beraldoleal can you upload the syslog over here so we can debug it?

**Comment by beraldoleal** [comment]
I don't have it anymore. Sorry. Let's create some stress tests to see if this is still happening.

**Comment by abaruchi** [comment]
I'll try to reproduce this behaviour. Initial tests do not seems to log twice the controller shutdown.

**Comment by diraol** [comment]
As far as I remember we have fixed all leaks. I'm closing this issue for now. If any other leak is found, reopen this issue.
