### ISSUE TITLE
Define methods to install/enable/disable NApps

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#141]
We need, on the ``Controller`` class, new methods to allow our users to install/enable/disable NApps without the need to manually manage directories and files around their OS.
All the NApp management should be done using only methods from our controller.

This issue aims to improve the usability of the Controller and its relationship with the NApps.

**Comment by diraol** [comment]
After implementing this features, we need to review and improve at least the README file from Kyco.

**Comment by cemsbr** [comment]
Moved to kytos-utils project (split into several issues).
