### ISSUE TITLE
Fix linter issues

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#148]
Fix output of `python setup.py lint`. Current issues (f58a3de6ce63c0cad8296a388d7eeba26aea60e0) are (number of occurrences, code and meaning):
- 3 R0201 = Method could be a function
- 1 R0911 = Too many return statements  (7/6)
- 1 R0914 = Too many local variables (17/15)
- 3 W0212 = Access to a protected member of a client class
- 3 W0223 =  Method is abstract but is not overridden
- 22 W0511 = TODO
- 1 W0621 = Redefining name 'log' from outer scope
- 1 W0703 = Catching too general exception Exception
- 2 W1505 = Using deprecated method async()

**Comment by cemsbr** [comment]
Build (and tests) will only fail on linter errors. After solving the warnings, we make it fail on warnings, too, like python-openflow. To check for warnings, comment out the line that starts with _disable_ in _setup.cfg_.

**Comment by beraldoleal** [comment]
@cemsbr can we close this ?

**Comment by cemsbr** [comment]
@beraldoleal, this situation remains exactly the same. We still should remove "python setup.py lint" warnings, including writing many issues from TODOs.

**Comment by cemsbr** [comment]
All TODOs can be found in #325.
