### ISSUE TITLE
Remove pip dependency from setup.py

### ISSUE THREAD

**Issue by macartur** [kytos/kytos#173]

**Comment by cemsbr** [comment]
@macartur, is this solved?

**Comment by beraldoleal** [comment]
@macartur ?

**Comment by macartur** [comment]
This dependency was removed only in kytos, but not in kytos-napps, kytos-utils and napps-server.

**Comment by beraldoleal** [comment]
@macartur I'm closing this. Please open specific issues on specific repositories.
