### ISSUE TITLE
Remove Config/options mandatory argument from controller

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#212]
Allow the controller start without the need of passing the ``options`` attribute. (If none is passed, then the controller should instantiate its own default version)

**Comment by cemsbr** [comment]
@diraol, what exactly do you mean by *controller start*? Currently, we can use *kytosd* without options.

**Comment by beraldoleal** [comment]
@cemsbr I think that is about `controller.start()` on console.

**Comment by diraol** [comment]
Actually I think I was talking about the `__init__` method.... But this may be already fixed.
