### ISSUE TITLE
Enable Scrutinizer

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#217]
Support for Travis and coveralls were added in PR #213. We need a Kytos admin to just enable these sevices

**Comment by beraldoleal** [comment]
Travis is already here. What was the integration app that you found ? I remember that you said a different than coveralls.

**Comment by diraol** [comment]
@cemsbr and @beraldoleal are we going to use scrutinizer on this repo too? If so, I think that this issue can be closed in favor of another one to setup scrutinizer here, right?

**Comment by beraldoleal** [comment]
@diraol Yes. We are still testing Scrutinizer. But yes, probably this will be scrutinizer too.
