### ISSUE TITLE
Rename author to username

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#220]
_Author_ will be something like "My Full Name <my@email.com>". Now, we use the word _author_ meaning _username_, not _Author_. Thus, we should rename current _author_ to _username_ in code and documentation of all projects.

**Comment by renanrodrigo** [comment]
I have branches changing this in kytos, kytos-utils and kytos-napps. Need help with the NApps Server though.

**Comment by beraldoleal** [comment]
@macartur ^
