### ISSUE TITLE
Move NAppsManager from kytos-utils to core

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#223]
All the code in ``NAppsManager`` is found in kytos-utils project.

**Comment by beraldoleal** [comment]
Maybe kytos-utils should create modules `kytos.utils.*` and both "kytos core" and "kytos cli" can use this ?

**Comment by cemsbr** [comment]
Such module already exists. Let me give you more details about both classes named *NAppsManager*: *kytos.core.napps_manager* code is part of the *kytos.utils.napps*. *kytos* (this project) could import *NAppsManager* from *kytos.utils* and we then we would be able to remove the code from here. As a result, *kytos* would depend on *kytos-utils*. Is this OK?

**Comment by beraldoleal** [comment]
I think that we should discuss this better thinking on a more distributed architecture. 

`kytos.core.napps.manager` (or something with a better name), should only execute actions related to kytos core. Imagine that we would like to create a event, let's say `kytos.core.napps.enabled`. This event should be created here.

`kytos.utils.napps.manager` for sure could have code that is used for multiple projects (outside core).

I'm working on "distributed kytos" allowing to have multiple kytos instances, and probably enabling one NApp at "master kytos instance" MUST trigger a kind of notification to all other instances. (Thinking about HA).

**Comment by cemsbr** [comment]
In this case, @beraldoleal, I believe that the more complete NAppsManager of *kytos.utils* that executes filesystem operations (download NApps, install, etc) would stay where the core is (either in the same project or in a separate one), and the kytos-utils would be something simpler like a REST client.

I believe we can postpone this discussion until then.

**Comment by hdiogenes** [comment]
We've done precisely what's described in the last comment, the last change being the REST API exposed from the core in #903.
