### ISSUE TITLE
Wrong comparision in class Interface

### ISSUE THREAD

**Issue by ajoaoff** [kytos/kytos#228]
One of the comparisions in method `__eq__` is comparing `self` instance with itself:
```
if self.switch.dpid != self.switch.dpid:
            return False
```
should be
```
if self.switch.dpid != other.switch.dpid:
            return False
```

**Comment by beraldoleal** [comment]
@cemsbr @diraol @macartur  this is was fixed, already, right ? Can we close ?

**Comment by cemsbr** [comment]
We fixed this issue in the same day it was reported.
