### ISSUE TITLE
Interface.is_link_between_switches always returning False

### ISSUE THREAD

**Issue by ajoaoff** [kytos/kytos#230]
The method `is_link_between_switches` in class `Interface` tests if the endpoint is an instance of `Interface`, but it is always a MAC Address.
I've done the following test: start mininet with a linear topology of 2 switches. The endpoint of one of the interfaces in the first switch is the MAC Address of one interface in the second switch, so it is a link between switches, but the test fails.

**Comment by beraldoleal** [comment]
Thanks @ajoaoff. We are going to check this soon. So I'm moving this to 2017.1b2 release.

**Comment by erickvermot** [comment]
proposition:

napps/kytos/of_core/main.py
l 103
- `address=port.hw_addr.value,`
+ `address=port.hw_addr,`


looking for other erroneous inits.

**Comment by macartur** [comment]
@ajoaoff , @beraldoleal, running the mininet with linear topology and 2 switches I got the endpoints:
 `[(HWAddress(00:00:00:00:00:01), datetime.datetime(2017, 3, 28, 17, 54, 56, 826459, tzinfo=datetime.timezone.utc)), (<kytos.core.switch.Interface object at 0x7f062004ac18>, datetime.datetime(2017, 3, 28, 17, 55, 0, 479344, tzinfo=datetime.timezone.utc))]` with HWAddress and Interface. Perhaps the old version of python3-openflow is installed, try install the last version.

**Comment by cemsbr** [comment]
I also tried to reproduce this bug, but couldn't. @ajoaoff, please, reopen this issue if you experience the same behavior in latest version.
