### ISSUE TITLE
Website kytos.io is not accessible

### ISSUE THREAD

**Issue by brennerm** [kytos/kytos#250]
I'm trying to reach your website and the documentation of the Kytos project but I'm getting a 403 or 404 for all pages.

**Comment by beraldoleal** [comment]
hi @brennerm, sorry about that. We are releasing a new website next Friday (24th Mar). Until there, please try to access:

docs.kytos.io/kytos/
docs.kytos.io/python-openflow/
docs.kytos.io/kytos-napps/

**Comment by brennerm** [comment]
Hi @beraldoleal,

Thanks for making the documentation available again.

Looking forward to have a look at your new website.
