### ISSUE TITLE
Fix namespace conflict

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#253]
Because of the current projects renaming, we now have a problem regarding python namespace between this project and the `kytos/kytos-utils` project. Both namespaces are `kytos`.

This makes the first one to be installed to work, while the other cannot be accessed.

**Comment by diraol** [comment]
On the link below there is a solution to "join" the namespaces between multiple python packages.

http://peak.telecommunity.com/DevCenter/setuptools#namespace-packages

**Comment by beraldoleal** [comment]
Our exact problem:

http://stackoverflow.com/questions/454691/putting-separate-python-packages-into-same-namespace

**Comment by diraol** [comment]
@beraldoleal we do have an even bigger problem.

On the current project we have ``kytos/utils.py``.
And on the `kytos/kytos-utils` project we have `kytos/utils/<xyz>.py`.

I think that it may not be possible to fix this kind of naming conflict without renaming one or another or adding one more level. =/

**Comment by beraldoleal** [comment]
@diraol I think that @cemsbr and I fixed this, at least temporally.

Please check our last commits on kytos and kytos-utils. Check if works for you, and close this if so.

Thanks a lot.

**Comment by diraol** [comment]
@beraldo and @cemsbr, things seems to be working now, except for one detail.

The ipython autocomplete *does not work* for both projetcs at the same time, unless you type it for the first time.

Exemplifying:
* Create a new empty virtualenv (`mkvirtualenv kytos -p /usr/local/bin/python3.6`)
* Enable the virtualenv... (`workon kytos`)
* Install all *python-openflow* dependencies: `pip install -r requirements.txt`
* Install *python-openflow*: `python setup.py install`
* Install all *kytos-utils* dependencies: `pip install -r requirements.txt`
* Install *kytos-utils*: `python setup.py install`
* Install *kytos* dependencies: `pip install -r requirements.txt`
* Install *kytos*: `python setup.py install`
* Install *ipython*: `pip install ipython`  (just to make sure we are using an ipython under our venv)
Open the *ipython* shell, type `from kytos.`  and press TAB to autocomplete.
You will only see `kytos.cli` and `kytos.utils` options.
But, if you type `from kytos.core.` and press TAB to autocomplete, some other options will show up and, more than that, now `from kytos.` + TAB will show `kytos.cli`, `kytos.core` and `kytos.utils`.

This will last until you close and open again your ipython shell.

I don't know if this is a big problem at all, but it may be. Specially if `kytos.core` is the one that is not being shown.

**Comment by beraldoleal** [comment]
@diraol few comments:

python setup.py install MUST automatically install requirements. I think that is already working this on all projects.

About the tab auto complete, can you, please open another issue and close this ?

**Comment by diraol** [comment]
#259 created
