### ISSUE TITLE
Fix kytos sub-projects dependencies

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#254]
On `requirements.txt` we have `python-openflow` as a dependency with a specific version (`>= 1.1.0b0.post1`). Since we do not have any releases for now, this may not work for a specific lib version. The same applies for `kytos-napps` (`>= 1.1.0b0.post1`)

So, it would be better to just add `python-openflow` and `kytos-napps` as dependencies, independently of the version.

**Comment by beraldoleal** [comment]
Agree
