### ISSUE TITLE
Problem with ipython autocomplete under kytos namespace

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#259]
Since our `kytos` and `kytos-utils` projects share the same python namespace, the ipython autocomplete does not work for both at the same time, unless you "force" type them for the first time.

Exemplifying:
    Create a new empty virtualenv (`mkvirtualenv kytos -p /usr/local/bin/python3.6`)
    Enable the virtualenv... (`workon kytos`)
    Install python-openflow: `python setup.py install`
    Install kytos-utils: `python setup.py install`
    Install kytos: `python setup.py install`
    Install ipython: `pip install ipython` (just to make sure we are using an ipython under our venv)
    Open the ipython shell, type `from kytos.` and press TAB to autocomplete.
    You will only see `kytos.cli` and `kytos.utils` options. [considering that you are *not* at the kytos directory]
    But, if you type `from kytos.core.` and press TAB to autocomplete, some other options will show up and, more than that, now from `kytos.` + TAB will show `kytos.cli`, `kytos.core` and `kytos.utils`.

This will last until you close and open again your ipython shell.

I don't know if this is a big problem at all, but it may be. Specially if kytos.core is the one that is not being shown.

**Comment by cemsbr** [comment]
This was fixed by implementing namespace packages.
