### ISSUE TITLE
Remove releases from Pypi

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#260]
We need to remove our old releases with older naming rules from pypi.
* https://pypi.python.org/pypi/kyco/1.1.0b1.dev1
* https://pypi.python.org/pypi/kyco-core-napps/1.1.0b1.dev1
* https://pypi.python.org/pypi/python-openflow/1.1.0b1.dev0

**Comment by beraldoleal** [comment]
I think that during the b1 release day we have to remove them and upload the new one. kyco-core-napps can be removed.

**Comment by beraldoleal** [comment]
Thanks @diraol . I just removed `kyco` and `kyco-core-napps`.

Next Friday we should upload with new version schemes.
