### ISSUE TITLE
Follow PEP420

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#265]
Enhance solution of 20f970778488e91414b8161bd4f317eb094d4d93 by following https://www.python.org/dev/peps/pep-0420.

**Comment by beraldoleal** [comment]
@cemsbr is #259 related ?

**Comment by cemsbr** [comment]
Yes, it is related, @beraldoleal, and I'll close that issue. I'm closing this issue since PEP420 is not active yet.
