### ISSUE TITLE
Can't run mininet inside of the Docker image

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos#267]
The kytos/tryfirst docker image does not have all the necessary tools and environment to run Mininet. We need a Kernel which supports network namespaces (and need that enabled, up and running), besides tools like iptables and net-tools.

**Comment by diraol** [comment]
@macartur has done it and sent the dockerfile to me, I've made a PR on the docker repository to @beraldoleal with the proposed changes. Thus, this issue can be closed (after the PR is accepted).

**Comment by beraldoleal** [comment]
@macartur with your changes I saw that all packages installations are commented. Any reason ?

**Comment by beraldoleal** [comment]
I think that @macartur fixed this and I uploaded a new docker image. Can you guys, test please ?

**Comment by beraldoleal** [comment]
Now, is working. If someone face this problem again, please reopen this.
