### ISSUE TITLE
Move kytos-admin-ui to here

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#269]
Today the admin needs to start a webserver point to kytos-admin-ui by itself. We need to move to this repo and make flask (for now) manage this with a simple route.

**Comment by diraol** [comment]
In order to preserve the repo history, I suggest that someone, on the admin-ui repo, create a new folder (`kytos/admin_ui`), move (`git mv`) all files to this folder, do the commit, and, then, add this repo as a remote repository and do the proper merge between both repos, keeping the git history from both projects.

**Comment by beraldoleal** [comment]
@diraol good point. I would suggest to move to `kytos/webserver`, `kytos/frontend`, `kytos/web-ui`, or `kytos/interface`

**Comment by renanrodrigo** [comment]
There are some points about this change I'd like to discuss. In priprority order:
1. As I have been reading, Flask is far from being the best option to serve static Html. Will we stick to it to serve the admin-ui web interface?
2. The css stuff is all written in sass and precompiled. Will the average network admin have to install ruby, the sass gem and stuff? If the answer to this is yes, then I think it makes sense to make it optional.
3. Overcoming the above problems, should the html/css/js code be refactored to suit Flask defaults? The directory structure should be changed, templates might be created.

**Comment by beraldoleal** [comment]
@renanrodrigo about your questions:

1. In production envs we will provide an apache and nginx to host this. For now, for dev and tests yes we will use flask;

2. python3.6 setup.py install MUST take care of all install stuff. Eventually we can think in how to improve this on the future and distribute a compiled minified version of all css stuff.

3. Please, can you create a better for this item ?

**Comment by renanrodrigo** [comment]
Sure;

3. Serving the static html files as I did in the PR (using serve_from_directory) is a short blanket: it covers our problem, but may lead to trouble in the future. To do it 'the Flask way' we'd use serve_template, which implies the need for a template folder with the index.html file inside. The .html itself shouldn't have relative paths in the .js and .css imports, but templates to load the path Flask gives to those files.
I'm no Flask specialist though, therefore unable to measure how changes like that would be needed and how much it would affect the behaviour of the applications overall.

**Comment by beraldoleal** [comment]
We will change this soon. We are planning a complete refactoring on how web view is exported.

Thanks.

**Comment by diraol** [comment]
Regarding the first point, about Flask, I would say that for the purpose of this web-ui (network administration), Flask is more than enought. This is not intended to be a public website, thus, I wouldn't expect more than a dozen of simultaneous sessions for a controller.

And, if one has a special need, it can use any webserver setup (such as Apache and nginx as @beraldoleal said) to serve the web interface (even with some kind of cache or other crazy wanted setup).
