### ISSUE TITLE
update requirements.txt

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#271]
- include comment for python3.6 requirement
- include comment for setuptools requirement

**Comment by beraldoleal** [comment]
I think that python3.6 requirement is already on README.rst. But setuptools is more complicated. `python3.6 setup.py install` will fail if your distro don't have setuptools.

**Comment by erickvermot** [comment]
should we make setup.py display a warning and abort in case setuptools is not installed?
@cemsbr @beraldoleal

**Comment by cemsbr** [comment]
Please, check the installation in a clean Ubuntu Server 16.10. We should catch any exception of pip install kytos.

**Comment by erickvermot** [comment]
I've been doing it on a clean base archlinux. I hope that's ok.

**Comment by cemsbr** [comment]
We must do it with Ubuntu 16.10 because that's what we claim to support.

**Comment by erickvermot** [comment]
I do not have a ubuntu server 16.10 system here.
@beraldoleal ? should I stop testing it on a base arch?

**Comment by beraldoleal** [comment]
@erickvermot @cemsbr No, we should support other distros too. But for now, for this release let's focus on Ubuntu only.

@cemsbr Regarding the try... except during import setuptools on setup.py, is already working ?

**Comment by diraol** [comment]
The try/except is there, as you asked to be.
