### ISSUE TITLE
Web modules per napp

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#281]
NApps should be able to create "views" on frontend by a simple API. Also with support to templates (like jinja2) in order to reuse code.

**Comment by diraol** [comment]
I'm looking for alternatives for this issue. For this reason, I'll put here some links about technologies and architectures that may be useful for us.

 - https://medium.com/javascript-scene/top-javascript-frameworks-topics-to-learn-in-2017-700a397b711
 - https://colorlib.com/wp/javascript-frameworks/
 - https://vuejs.org/
 - https://angular.io/
 - https://facebook.github.io/react/

Later I'll try to improve and/or add comments here.

**Comment by diraol** [comment]
Another suggestion was Framework7, and build our own framework based on Backbone.js.
I am still evaluating these possibilities and gathering suggestions from friends.

**Comment by hdiogenes** [comment]
Already possible with Vue.js components. Docs in:
* https://docs.kytos.io/admin/web-ui/
* https://github.com/kytos/ui/blob/master/docs/source/index.rst
