### ISSUE TITLE
Blueprint: OpenFlow Hanshake

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#284]
Discussion related to OF hanshake and version negociation.

- [x] move blueprint from python-openflow wiki to kytos repo.
- [ ] discuss and update blueprint.

**Comment by erickvermot** [comment]
I believe there should be clear separation beetween the establishment of the transport connection, and the openflow negotitation. It gives a more clear view of what's happening, and it may also allow for the controller to operate with different protocols in the future. 

I wrote a small draft for you guys to take a look.
>

**Comment by erickvermot** [comment]
sorry, it was meant to be read as a draft for a new blueprint, and not necessarily remove all that is not in the file...
I think we could separate things that are not directly related to the handshake. The handshake can be considered completed after the version is decided in the negotiation process, and a ``kytos/of_core.hello_complete`` or ``kytos/of_core.hello_failed`` event could be triggered.
It is important to note that after a hello_failed, the connection must be terminated, but only after the hello_failed message is sent, and not only put or taken from the queue.

I believe maybe the details of the FeaturesRequest response should be specified separately, and not in the handshake blueprint, as I believe you can send a FeaturesRequest at any moment.

[this commit](https://github.com/kytos/kytos-napps/compare/master...erickvermot:issue_166) proposes something in that direction.

What is still missing in the file is the specification of the negotiation process, which involves determining the version of the protocol to use with this connection. The implementation of the version decision involves a bitwise AND of the incoming VERSIONBITMAP with the bitmap of the capable versions of this implementation that could be located as an attribute of the of_core napp.
It is marked as a TODO in the commit.

**Comment by erickvermot** [comment]
Once the handshake is complete and the hello_complete event is triggered, there must be a mechanism to assert the communications restrictions imposed by the selected OpenFlow version for the connection, and how the different apps and maybe even of_core will respond to that.

**Comment by erickvermot** [comment]
Some issues regarding the TCP_server need to be fixed as well: #292 .

Also, this [pyof-EP01-draft](https://github.com/erickvermot/python-openflow/blob/pyof_ep_01/docs/blueprints/pyof-EP01-draft.rst) includes some comments on how the correct parser version could be associated with the connection.

**Comment by cemsbr** [comment]
@erickvermot, is this still valid after handshake implementation or we can close the issue?

**Comment by erickvermot** [comment]
@cemsbr this was implemented in https://github.com/kytos/kytos/pull/460,
we can close the issue.
