### ISSUE TITLE
python-daemon dependency

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#291]
We have to keep tracking on python-daemon upstream if the bug is fixed in order to use back upstream.
@cemsbr please add more information here.

**Comment by diraol** [comment]
is there any version of python-daemon that fits our needs and does not present the given bug? If so, we can just pin python-daemon on that specific working version, and update it on the future, after the bug is fixed.

**Comment by cemsbr** [comment]
The requirement is python-daemon>=2.1.2. Thus, it will install version 2.1.3 or later from upstream, when available. If upstream works, we can remove the link to my fork from setup.py and update the version number in the requirements.

I also subscribed to upstream's repo and wrote about my fork in the appropriate issue. When I see an e-mail about a new version, I'll run the steps above. But anybody can feel free to do it.

**Comment by beraldoleal** [comment]
Thanks @cemsbr .

**Comment by cemsbr** [comment]
I removed the milestone because we don't know when and if upstream will release a new version.

**Comment by diraol** [comment]
Since we are now using pip and wheel I think this issue can be closed, right @cemsbr ?

**Comment by cemsbr** [comment]
Right. Upstream's wheel works and we don't need the fork anymore.
