### ISSUE TITLE
Fix tcp_server

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#292]
Currently the tcp_server is strictly OpenFlow, and it does some of the parsing inside it's ``HandlerClass.handle`` method. This needs to change so that the controller can operate with different protocols, and protocol versions.
From what I understand about the wanted structure, OF parsing should be done by ``of_core`` napp, not by ``kytos/core`` or inside the handler. If this is the way to go, some things need to change:

- implement the tcp server so that it is initialized with a generic ``KytosRequestHandler`` instead of a specific Openflow one.
- implement the ``RequestHandler`` so that it triggers a ``kytos/server.data.in`` event with the raw bytes read from the socket.
- make the ``Connection`` hold info about it's state (new, setup, established, finished), and it's protocol.
- process the raw bytes received via the ``server.data.in`` inside ``of_core``. It includes slicing the raw data flow into packets, and parsing the initial hello message before the protocol version is set by the negotiation.

I believe the TCP server and the handler could be moved outside the core, to a new napp or inside ``of_core``, as was also suggested by @diraol. 

Maybe the Handler could contain ``protocol_pack`` and ``protocol_unpack`` functions set once negotiation is completed, that should be used to parse the incoming messages.

**Comment by diraol** [comment]
@erickvermot can we close this issue?

**Comment by erickvermot** [comment]
IDK, should we close it now, or should we close it when we move the whole TCP Server and handler to of_core? Or should we open another issue for that?
@beraldoleal @diraol

**Comment by beraldoleal** [comment]
This is a big issue, right ? So far I understood, we fixed part of this with @erickvermot PR. So I suggest to open a new issue, just to move tcp_server to outside core.

**Comment by beraldoleal** [comment]
I'm closing this issue, if there is any issue here that is not splited as new issue, please open a new specific issue.
