### ISSUE TITLE
Improve projects packages 'descriptions' [PEP301]

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#296]
Our projects packages can have their metadata improved, specially by adding Classifiers. They can help the project to be discovered, among other things.

Ref: https://www.python.org/dev/peps/pep-0301/#id24

**Comment by diraol** [comment]
Btw, I've found this beauty: https://pypi.python.org/pypi?%3Aaction=list_classifiers

**Comment by abaruchi** [comment]
Based on linked passed by @diraol in last comment, I guess that for kytos project we can add the following indexes labels: 

**Apply to all repos:**
Framework :: Sphinx
Development Status :: 4 - Beta
License :: OSI Approved :: MIT License
Operating System :: POSIX :: Linux
Programming Language :: Python :: 3.6
Topic :: System :: Networking

**Olny for the controller Kytos (daemon):**
Environment :: Console
Environment :: No Input/Output (Daemon)

**Only for python-openflow:**
Topic :: Software Development :: Libraries

**Only for for kytos-napps:**
Environment :: Web Environment
Framework :: Flask

**Comment by beraldoleal** [comment]
@abaruchi we should not add Sphinx and Flask.

**Comment by abaruchi** [comment]
Ok. Agree.
Will check how to create this index.

**Comment by diraol** [comment]
Hum.... I don't have any idea why I reopened this issue, probably was by mistake. Sorry up guys, closing it.
