### ISSUE TITLE
Classes to be exposed on `kytos.core`

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#298]
In order to avoid unnecessary longer imports, we have decided to expose some classes directly on the `kytos.core` module (e.g.: `kytos.core.Controller` instead of `kytos.core.controller.Controller`). This will be done by importing the class to be exposed on the `__init__.py` file from the `kytos.core` module.

Eventually it would be good to do the same with some other classes, specially those that may be used more frequently by our users and by NApp developers.
I'll list some of our core classes bellow so we can think about what classes may be exposed directly on the `kytos.core` module, with the current import as is and if it is used in other "places" than the module itself:

 - *KytosEventBuffer* (`from kytos.core.buffers import KytosEventBuffer`) [used only locally on this module]
 - *KytosBuffers* (`from kytos.core.buffers import KytosBuffers`) [used on the controller module]
 - *KytosConfig* (`from kytos.core.config import KytosConfig`) [used on the controller module, on the daemon and may be used more broadly to setup new configs]
 - *KytosEvent* (`from kytos.core.events import KytosEvents`) [broadly used by the core and the NApps]
 - <flow_module> -> This may be removed from the core, since it is openflow specific, right?
 - *KytosNApp* (`from kytos.core.napps import KytosNApp`) [used by all NApps]
 - *Interface* (`from kytos.core.switch import Interface`)
 - *Connection* (`from kytos.core.switch import Connection`)
 - *Switch* (`from kytos.core.switch import Switch`)
 - <tcp_server_module> -> This may be removed in favor of a new NApp with the same function.

@beraldoleal Which of these classes may we expose directly on `kytos.core`?
`kytos.core.Controller`, `kytos.core.KytosConfig`, `kytos.core.KytosNApp` and `kytos.core.KytosEvent`?

**Comment by beraldoleal** [comment]
Good, for now let's keep only `Controller`, `KytosNApp` and `KytosEvent`.
