### ISSUE TITLE
Move existing and update blueprints from wiki

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#300]
Move existing blueprints from wiki to kytos/docs/blueprints, and rename them sequentially.

**Comment by diraol** [comment]
@erickvermot and @beraldoleal can we close this issue?

**Comment by erickvermot** [comment]
I think we could update their references, structure and markup before closing...

**Comment by beraldoleal** [comment]
All blueprints were moved ? If yes, we can close.

**Comment by erickvermot** [comment]
All I could find on the wikis of each project.
I still have to delete the wikis though. I have not deleted yet because I wasn't sure if you would want to keep track of the past changes on the blueprints.

**Comment by beraldoleal** [comment]
@erickvermot no, you can delete the wikis also. No problem.

**Comment by erickvermot** [comment]
wikis deleted. closing the issue.
