### ISSUE TITLE
Check if decorators name is conforming any pep

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#32]
Decorators based on methods are all lower case. Some examples on Internet with decorators based on classes (not class decorators) are also lower case.

Lets make sure that we are not breaking any pep, here.

**Comment by diraol** [comment]
As stated here:
https://www.python.org/dev/peps/pep-0008/#class-names

> The naming convention for functions may be used instead in cases where the interface is documented and used primarily as a callable

So we can use the class named as a function.
But I've modified the decorator to be a function instead of a class, which also solves the 'problem'.
