### ISSUE TITLE
Add tryfirst to readme

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#320]
We need to add a section to our docker image before installing.

**Comment by diraol** [comment]
@erickvermot Can you handle this, since you have been dealing with the Docker for the past few days?

**Comment by erickvermot** [comment]
@diraol, I've been dealing with some mininet problems, not docker... 
I can handle it if you guys want, but I've not understood the flag --privileged
you said to pass for example.
Should there be an explanation?

**Comment by beraldoleal** [comment]
@erickvermot no explanation for now. Just a line with something like:
"If you want to try kytos first, without install please run the command below:"

**Comment by erickvermot** [comment]
is this ok?


Try First
=========

You may try kytos without installing it by running our docker image.
Just install docker from your package provider and run:

.. code-block:: shell

   $ sudo docker run -it kytos/tryfirst /bin/bash

and you may skip the ``Installing`` section.

**Comment by erickvermot** [comment]
should we include some troubleshooting about how to remove a previous image?

**Comment by beraldoleal** [comment]
@erickvermot perfect. About remove previous image, is not necessary.

Thanks.
