### ISSUE TITLE
Kytos installation is taking much time

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos#332]
Especifically, `python-daemon` and `docutils` present some warnings and take too long to finish installing.

**Comment by diraol** [comment]
Regarding `python-daemon`, this may be due to the fact that our current install process install it from @cemsbr git fork [since the upstream is bugged]. So, cloning, building and installing may be taking longer than it would if the install was from an already built package. So, maybe we would try to create the packet already built and install from it.

**Comment by cemsbr** [comment]
Building python-daemon seems to be slow and the only way to make it faster is to provide the package somehow. Besides, the iPython dependency made the install process even longer.

**Comment by cemsbr** [comment]
We can use wheels ([Wheels vs Egg](https://packaging.python.org/wheel_egg/)) to speed up the install process. As a (good) side effect, we won't need our fork of python-daemon anymore because its wheel works (many projects have [migrated to wheels](http://pythonwheels.com/)).

**Comment by cemsbr** [comment]
We need an update of python-openflow in pypi: https://github.com/kytos/python-openflow/issues/359

**Comment by cemsbr** [comment]
The python wheel of my branch "wheel" has the following error:
```
PYTHONPATH=build/bdist.linux-x86_64/wheel python setup.py bdist_wheel
pip install dist/kytos-2017.1b1-py3-none-any.whl
Processing ./dist/kytos-2017.1b1-py3-none-any.whl
Installing collected packages: kytos
kytos is in an unsupported or invalid wheel
```

**Comment by cemsbr** [comment]
Solved with the help of @diraol and @macartur. It is much faster now, @beraldoleal! In a clean environment with pip (maybe wheel package, too), run `pip install https://github.com/cemsbr/kytos/releases/download/wheel/kytos-2017.1b1-py3-none-any.whl`
