### ISSUE TITLE
Define the xid default behaviour for OpenFlowMessages

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#35]
We need to define if the answered messages will have the same xid of the received messages and also we need to decide a rule to generate a random xid for new messages that will be sent to the 'clients' (switches).

**Comment by beraldoleal** [comment]
According to an [openflow-spec mail list message](https://mailman.stanford.edu/pipermail/openflow-spec/2011-January/001533.html):

"The purpose of an xid is to match up a request and its reply.  An asynchronous message is not a  reply, and does not receive any replies, so it is not useful in asynchronous messages.  OVS sets the xid to 0..."

May be they are talking about the switch point of view, but I think that is unsafe to assume that new xid should be 0.

For now, lets just generate a random number for new messages between 0 and maximum allowed in xid. And the same xid when is a reply.

**Comment by diraol** [comment]
Ok.

So, regarding the `Kyco` project the only important part of this issue is to reply messages with the same xid of the 'request' message.

The randomness of the xid should be provided by the [`python-openflow`](https://github.com/kytos/python-openflow) library as the default behaviour of the xid attribute. (I'll create an issue over there to do this)

Should we create a new Blueprint (here and/or on [`python-openflow`](https://github.com/kytos/python-openflow) repo) to document this and guide future app developers that this is the expected behavior?

**Comment by beraldoleal** [comment]
Yes, we should create an issue on python-openflow for this, thanks @diraol.

I don't think that there is a urgent need for a blueprint now. I would recommend just document on issue there and on the future, we can create a blueprint too.

But if you feel comfortable to write this blueprint, great, go ahead.

**Comment by diraol** [comment]
Blueprint created.
https://github.com/kytos/kyco/wiki/Blueprints-messages-xid

Closing the issue.
