### ISSUE TITLE
Consider a problematic KytosNApp.setup()

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#359]
TODO: If the setup method is blocking, then the execute method will never be called. Should we execute it inside a new thread? -- from [this line](https://github.com/kytos/kytos/blob/379421a12d883554c02e8279397aa8fad41e4786/kytos/core/napps/base.py#L208).

For example, if a NApp has an infinite loop in setup method, the controller will be blocked.

**Comment by hdiogenes** [comment]
This happens inside the `KytosNApp` class, which is already a different thread from the Controller, so all that will block is the NApp itself.
