### ISSUE TITLE
kytosd -D debug option not working

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#363]
when starting the Deamon with the -D option the debug messages are still not shown. 

changing from INFO to DEBUG in ``/etc/kytos/logging.ini`` does not work either.

**Comment by beraldoleal** [comment]
This should work. Thanks for reporting this.

There is another open issue #315 related to this. Let's fix this on b3.

**Comment by erickvermot** [comment]
logging level is being set at kytos/core/logs.py (line 10), and never again.

workaround for now is explicitly changing the level...
``logging.basicConfig(format=FORMAT, level=logging.DEBUG)``

**Comment by beraldoleal** [comment]
@erickvermot this is more tricky. We have to use `logginig.ini` file with multiple log handlers.

Please keep this change locally for now at your branch. DEBUG was removed intentionally .

**Comment by erickvermot** [comment]
@beraldoleal I know, I only mentioned a workaround so I can see the debug logs for now. It is not a fix.
It is not meant to change anything.
