### ISSUE TITLE
setup install doesn't install dependencies

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#367]
`python setup.py install` is not installing deps listed in requirements.txt (i.e. `pip freeze | grep daemon`). However, `pip install git+https...` works. As a reference, kytos-utils works.

**Comment by cemsbr** [comment]
As @macartur pointed out: pypa/setuptools#456.

**Comment by renanrodrigo** [comment]
Isn't this related to #357 ?

**Comment by diraol** [comment]
Yes, this is the same issue.

**Comment by cemsbr** [comment]
This is the cause of the other that issue. I'm marking this as duplicate because it is the more recent one and we have references.
