### ISSUE TITLE
Enhance pidfile creation to support execution as non-root user

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos#368]
Since we are generating a pidfile in `/var/run`, `kytosd` needs root permission to be executed outside a virtual environment. Need to check pidfile creation to support common users running kytosd.

**Comment by diraol** [comment]
To run as a "common" user, I'm installing kytos on a virtualenv. So, may be just putting the pidfile inside `${BASE_ENV}var/run` (examples can be found inside our codebase) would solve this problem.

**Comment by renanrodrigo** [comment]
@diraol It is already done this way, there is no problem with the execution in virtualenvs. The only downside is observed when trying to run directly in the base system.

**Comment by diraol** [comment]
Ok, @renanrodrigo. So I think the best solution here is:
1) While installing kytos on the system, create a group named `kytos`.
2) Create a directory `/var/run/kytos`
3) Set the group ownership of `/var/run/kytos` to `kytos` group.
4) Set the permission of `/var/run/kytos` to `775` with `setgid bit` [`chmod g+s /var/run/kytos`].
Eventually we can also use the `DELETION FLAG OR STICKY BIT` feature too. (see `chmod` man page for more info)
5) Add the current user to the `kytos` group.

@beraldoleal what do you think about it?

**Comment by beraldoleal** [comment]
@diraol I will accept PR #369 like it is, for now. A better and improved solution we can do on future releases.

Your proposal is valid and ok, except item 4. I'm not sure if we need g+s. Also we have to take in consideration that user/group is informed by user at `/etc/kytos/kytos.conf`. We have to start to think on how to pass theses values to setup.py during install procedure. For instance debian has post-install scripts that helps on that.

**Comment by diraol** [comment]
Ok @beraldoleal no problems (despite a `777` directory rs).

Regarding the `g+s` I've just proposed it in order to avoid a user creating a pidfile that can't be "edited" by other users. It (`g+s`) will make the `group` of any file under that directory to be the `kytos` group (or any other that was defined to be), in such a way that any user from that group will still have permissions on the content of the directory.
