### ISSUE TITLE
Load Jinja2 during kytos setup

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#370]
After solving kytos/kytos#357 we still have an error during our setup.

`Jinja2` is a requirement of our project (it is in requirements.txt), and is correctly installed by the `setup` procedure (`python setup.yp install`).
But as it is also used/loaded on the setup script, we are facing a `timing` problem.

The available (installed) modules from `PYTHONPATH` are loaded on the beginning of the `setup.py` script. During this script, all requirements are installed, including the `Jinja2` package. But the available modules (`sys.path`) are not reloaded, thus `Jinja2` is not available to be used inside the `setup.py` script, which raises an error during the install procedure.

If the setup is run again, everything works fine (since `Jinja2` was installed on the first run).

So, we need  to figure out how to load (import) `jinja2` on the `setup.py` script "on the runtime".

**Comment by beraldoleal** [comment]
@diraol try... except... import on proper place will not work ? Besides that.. We have to figure out what is the best way to get values from "user/config file" during setup procedure.

**Comment by diraol** [comment]
@beraldoleal we can use a try/except over there, no problem. But if the `Jinja2` package was installed during the install procedure it will not be available to the importer on any part of the setup script without `reloading` the packages available on the sys.path.

Regarding the "user/config file", I didn't understood what value should we get from user/config file that would alter anything related to this issue....

**Comment by beraldoleal** [comment]
@diraol exact.
```
try:
  import jinja2
except ImportErrorBlabla:
  do your function to insert to the path here
```

Makes sense ?

**Comment by diraol** [comment]
Yeap, no problems with that. =)
