### ISSUE TITLE
Tests for 2017.1b2 release

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#379]
Tests:

 - [x] **Install** via **pip** on the system as root
    - [x] run daemon
    - [x] run foreground
    - [x] mininet pinging
    - [x] test web ui
 - [x] **Install** via **pip** on a virtualenv as root
    - [x] run daemon
    - [x] run foreground
    - [x] mininet pinging
    - [x] test web ui
 - [x] **Install** via **pip** on a virtualenv as a regular user
    - [x] run daemon
    - [x] run foreground
    - [x] mininet pinging
    - [x] test web ui
 - [x] **Install** from **source** on the system as root
    - [x] run daemon
    - [x] run foreground
    - [x] mininet pinging
    - [x] test web ui
 - [x] **Install** from **source** on a virtualenv as root
    - [x] run daemon
    - [x] run foreground
    - [x] mininet pinging
    - [x] test web ui
 - [x] **Install** from **source** on a virtualenv as a regular user
    - [x] run daemon
    - [x] run foreground
    - [x] mininet pinging
    - [x] test web ui
 - [x] `kytos/try-first` docker
    - [x] install/deploy
    - [x] run daemon
    - [x] run foreground
    - [x] mininet pinging
    - [x] test web ui

**Comment by renanrodrigo** [comment]
I'm going to do these in an Ubuntu 16.04 environment. If @macartur could use another distribution, it'd be nice. Please tell me otherwise.

**Comment by erickvermot** [comment]
When installing on the system from source as root, I can no longer run kytosd as a normal user. This used to be possible before the commit about the pidfile.

**Comment by renanrodrigo** [comment]
Just a note: 
As some dependencies can't be installed using bdist_wheel, the install via pip presents some errors like `Failed building wheel for -some dependency-`. However, those dependencies are installed and running, so the tests are successful.

**Comment by erickvermot** [comment]
Tests I have done here.
OS: Arch linux
kytos: commit kytos/kytos@aa05413 May 5th
kytos-napps: commit kytos/kytos-napps@0fc1cb7 May 5th
python-openflow: commit kytos/python-openflow@6a3916fd May 3rd

 - [x] **Install** from **source** on the system as root
    - [x] run as root
    - [x] run as normal user (yes, but not after reboot. Needs to create /var/run/kytos [0o777])
    - [x] run daemon
    - [x] run foreground
    - [x] mininet pinging
    - [x] test web ui
 - [x] `kytos/try-first` docker (using --privileged)
    - [x] run daemon
    - [x] run foreground
    - [x] mininet pinging (after updating kytos-napps)
