### ISSUE TITLE
logs from switch.py are not showing

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#386]
after the update about the logs https://github.com/kytos/kytos/pull/377, some logs are not showing...

**Comment by beraldoleal** [comment]
@macartur can you check this, please ?

**Comment by macartur** [comment]
OK, I will check this problem.

**Comment by erickvermot** [comment]
@cemsbr, @macartur, @beraldoleal, 
for some reason some logs still do not show up... (for example logs from the new module connection.py in PR #374). Could you guys check if there is something that should be done in the module that is not being done, or if this is still some manifestation of this issue? Tks
[UPDATE] @macartur checked it, and a rebase solved the issue. apparently there has been a log refactor recently. tks
