### ISSUE TITLE
Communication tests not working in kytos/tryfirst docker image.

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos#390]
Mininet ping test is failing when using the kytos/tryfirst docker image.
Scenario:
- latest version of python-openflow, kytos-utils and kytos running inside the container.
- Mininet installed from the apt repository, running inside the container.
- Enabled NApps: kytos/of_core and kytos/of_l2ls.
- Any Mininet topology.

Mininet hosts are unable to ping each other. `ovs-ofctl dump-flows` command shows no flows installed in none of the switches.

**Comment by beraldoleal** [comment]
@renanrodrigo I accept a PR that probably fixes this. Please, can you confirm if the problem persists? If not, do you have more details ?

**Comment by renanrodrigo** [comment]
@beraldoleal problem solved. Communication seems ok now.
