### ISSUE TITLE
Wrong pid file location on config.py

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#398]
Setup.py creates the folder ``/var/run/kytos`` to hold the pidfile, but config.py is still referencing ``/var/run/kytosd.pid``

**Comment by beraldoleal** [comment]
@renanrodrigo @diraol ?

**Comment by renanrodrigo** [comment]
The template at https://github.com/kytos/kytos/blob/master/etc/kytos/kytos.conf.template has it at the correct folder.

**Comment by beraldoleal** [comment]
@renanrodrigo @erickvermot said about `config.py`, Is `config.py` with the correct path ?
