### ISSUE TITLE
Handle multiple open flow versions dynamically

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#4]

**Comment by cemsbr** [comment]
@diraol, with the class inheritance for new spec versions, I think it will be up to the user to specify the desired version in imports, solving this issue. Please, open a PR with the inheritance code referencing this issue and assigning me as a reviewer.

**Comment by diraol** [comment]
This is not a kytos related issue anymore, since kytos is now designed to be protocol agnostic. This must be addressed on `python-openflow` and on the `openflow` NApps (such as `kytos/of_core`, `kytos/of_l2ls` and so on)/
