### ISSUE TITLE
Create a smaller docker image

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#407]
Today our tryfirst has > 600 MB, let's try to reduce this number.

**Comment by diraol** [comment]
May be we can go with something like this image:
https://github.com/docker-library/python/blob/db2d58d73043c85ceecc8e675372b4dc6a77d136/3.6/slim/Dockerfile

**Comment by diraol** [comment]
And improve it using `debian:jessie-slim` as base image instead of `debian:jessie`

**Comment by diraol** [comment]
Just to keep everyone on the loop, I was able to create a minimal **base** image (`base-slim`), based on `debian jessie`, with python3.6 installed (only python3.6 + pip) with "164MB". Our current base image have 528MB, but it contains mininet, which I did not installed on the base image.

I'm working on a `base-slim-with-mininet` version.

And the new `tryfirst` (without mininet) have 286MB.

**Comment by beraldoleal** [comment]
Great work, but let's try to reduce this more drastically on next release.

**Comment by beraldoleal** [comment]
https://hub.docker.com/_/alpine/

I know that is not apt like but let's see if this is straightforward or not.

**Comment by diraol** [comment]
Should we look at it for this release @beraldoleal ?

**Comment by cemsbr** [comment]
Update: [tryfirst is now 116 MB](https://hub.docker.com/r/kytos/tryfirst/tags/) (download size). IMHO reducing this size doesn't worth the effort of compiling Mininet, for example. At least for now.

**Comment by hdiogenes** [comment]
Reduced from 600 MB to 116 MB by @diraol.
