### ISSUE TITLE
ghost hosts appearing in web interface

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#415]
There are some non-existing hosts appearing in the web-interface.
I believe @macartur was looking at this, is that right?

In the screenshot below I used a tree topology with depth=2 and fanout=2, which should show 4 hosts.
![2017-05-10-160311_1917x1007_scrot](https://cloud.githubusercontent.com/assets/10514972/25916290/7edec254-359a-11e7-873d-e836fffa197c.png)

**Comment by erickvermot** [comment]
they seem to represent unconnected interfaces... I don't really understand, but maybe it'll help someone figure it out.
![2017-05-10-161331_462x420_scrot](https://cloud.githubusercontent.com/assets/10514972/25916644/c3f2de7e-359b-11e7-9e55-0e9ec8c794e7.png)

**Comment by macartur** [comment]
- Each switch has one unconnected interface used to connect the switches to the controller.

- How you used the parameter `--mac` to run Mininet each host has a pretty address, for instance <00:00:00:00:00:00:00:01>, and each host appears as a red circle. In the first image, there are 4 hosts connected with one switch.

**Comment by renanrodrigo** [comment]
I found what are those.
We are generating 'hosts' for switch interfaces that are connected to other switches.

Please note that single-switch scenarios don't present any ghost host.
Note also that the mac address of the disconnected hosts always matches to the latter switch interfaces (if you are running Mininet, those connect the switches between themselves by default).

To fix this, we shall check connections between switches in the topology and do not generate hosts for those.
