### ISSUE TITLE
Correctly deal with `ConnectionResetError`

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#417]
On our `kytos.core.tcp_server` we are catching `ConnectionResetError` error. It seems to be a consequence of a reconnection from a switch.

As discussed on kytos/kytos#410 (https://github.com/kytos/kytos/pull/410#pullrequestreview-37288126), we may reset some parameters from the switch and the connection, such as the connection status - that should go back to the initial state, without handshake.

**Comment by beraldoleal** [comment]
What is the status of this ?

**Comment by diraol** [comment]
Doing a huge review of all issues, I've found kytos/kytos#50 which seems to be almost the same thing of this one. So, I'm closing this issue in favor of the older one.
