### ISSUE TITLE
Shutdown process

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#42]
We need to think about the shutdown process (workflow).

At this moment the `controller.stop()` closes the `KycoServer` socket, it shutdown (`KycoServer`) and sends a `KycoShutdownEvent` to all buffers, which makes them stop receiving new events.
But there still the possibility of new events being generated, such as `KycoSwitchDown`, `KycoConnectionLost`, among others.

So, how to deal with this timming?

**Comment by beraldoleal** [comment]
Yes, lets create a blueprint to document this.

**Comment by diraol** [comment]
I think this is solved, at least for now.
