### ISSUE TITLE
Setup does not take into account DESTDIR env variable.

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#425]
While trying to build the debian package for the project, we got the following error:
```
 dpkg-source --before-build kytos-2017.1b1
 fakeroot debian/rules clean
dh clean --with python3 --buildsystem=pybuild
   dh_testdir -O--buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:184: python3.5 setup.py clean
Traceback (most recent call last):
  File "setup.py", line 136, in <module>
    os.makedirs(napps_dir, exist_ok=True)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/kytos'
E: pybuild pybuild:283: clean: plugin distutils failed with: exit code=1: python3.5 setup.py clean
dh_auto_clean: pybuild --clean -i python{version} -p 3.5 returned exit code 13
debian/rules:8: recipe for target 'clean' failed
make: *** [clean] Error 25
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
I: copying local configuration
E: Failed autobuilding of package
```

This probably is due to the fact that our code does not take into account the `DESTDIR` environment variable that is used on the build process.
Here is an issue that seems to be related to the same problem we are facing:
https://github.com/savoirfairelinux/opendht/issues/72

But, instead of passing the responsibility of deal with this variable to the 'Makefile', which we don't have, we may evaluate this environment variable together with the `VIRTUAL_ENV` variable, while building the `BASE_ENV`. This may make our code easier to be deployed in multiple environments and also avoid specific "workarounds" for building the debian package, for example.

**Comment by beraldoleal** [comment]
@diraol wich user did executed this ? I can see a permission denied.

**Comment by diraol** [comment]
@beraldoleal this happened while building the debian package.

As far as I understood, what is happening is that it tries to build package by installing it into `DESTSDIR`, as if it was the `root folder`. Almost a `chroot`. But we are forcing, on the setup, the placement of some files on directories outside of this `chroot` environment used to build the `deb` package.

It is a similar situation to the `VIRTUALENV` case.

**Comment by erickvermot** [comment]
As I understand, it IS NOT setup.py's job to read the ``DESTDIR`` environment variable and use it appending to the paths it is using (as in https://github.com/kytos/kytos/compare/master...erickvermot:destdir and https://github.com/kytos/kytos-utils/compare/master...erickvermot:destdir).
The use of DESTDIR environment variable happens in the makefile, and should be passed to setup.py as a parameter (the ``--root`` parameter maybe)...

But for all of this to work as expected, setup.py should be written according to what setuptools expect from it (not writing files outside of the package for example, in arbitrary OS locations).
So I consider this to be highly connected with https://github.com/kytos/kytos/issues/471, and once this is solved, the process of transforming a python-package into a debian package should be simpler.

**Comment by diraol** [comment]
I'm closing this issue since the actual problem is not related to the evaluation of 'DESTDIR' env variable.
