### ISSUE TITLE
Consider `$DESTDIR` env variable

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#433]
While trying to create the debian package, @phls found some issues regarding our setup.py attempt to copy/move some files to absolute paths on the system, such as `/etc/kytos/<>`, which raises a permission denied error.

This must be due to the fact that the process to create a debian package is done under a kind of fakeroot path, set by the `$DESTDIR` variable, which we are not considering.

**Comment by beraldoleal** [comment]
@diraol @phls Debian has post-scripts right ? What is Debian recommendation when dealing with python packages ? Let python copy the files or do the job by post-scripts ?

**Comment by diraol** [comment]
Duplicated from #425
