### ISSUE TITLE
Add install docs

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#440]
From @beraldoleal: "O procedimento de instalação em docs.kytos.io esta faltando. Isso deve bater exatamente com a seção Install do README do kytos."

I believe this is about missing https://docs.kytos.io/kytos/installing/.

**Comment by cemsbr** [comment]
Updating the server fixed this.

**Comment by erickvermot** [comment]
https://github.com/kytos/documentation/pull/46/
