### ISSUE TITLE
Docs: missing parameter description

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#441]
From @beraldoleal about a user: _"... falou que na documentação estava faltando o pydoc descrevendo os argumentos dos métodos em algum lugar (ele nao me falou onde). Seria bom revisarmos isso. E tomar cuidado redobrado. Não sei se teria como o lint pegar esse tipo de "falta de documentação de argumentos"._

I couldn't find a tool for reporting missing parameter descriptions. We'd better wait for more details instead of searching through all the code of all our projects.

**Comment by diraol** [comment]
This must be addressed on the documentation review to be done until our stable Release.
