### ISSUE TITLE
Move the Kytos TCP Server from kytos/core to the of_core napp

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#446]
Following the discussions about the TCP server and the OF handshake, and the recent advances in this topic, the next planned step it to move the TCP Server from inside the controller core to the of_core napp. This will simplify many of the internal steps of the communication process, as well as allow the development of napps that communicate using other application protocols (instead of OF) of even other transport layer protocols (TLS instead of simple TCP for ex).

I'll list here other issues or links related to this discussion:

https://github.com/kytos/kytos/issues/49

https://github.com/kytos/kytos/issues/284
https://github.com/kytos/kytos/issues/292
https://github.com/kytos/kytos/issues/302

https://github.com/kytos/kytos/pull/374
https://github.com/kytos/kytos-napps/pull/217

**Comment by hdiogenes** [comment]
@beraldoleal I think we agree that this won't be done. Can we close the ticket?
