### ISSUE TITLE
[web-ui] There are strange objects

### ISSUE THREAD

**Issue by macartur** [kytos/kytos#463]
Firefox
---------
![kytos_firefox](https://user-images.githubusercontent.com/2965806/27341626-32f99546-55b4-11e7-9173-d5988a9edd70.png)

Google Chrome
---------------------
![kytos_google_chrome](https://user-images.githubusercontent.com/2965806/27344986-95ec81ea-55be-11e7-98b1-f0fce6081d23.png)

Description
---------------
Some objects related with MapBox appear in google-chrome and don't appear in Firefox.

**Comment by diraol** [comment]
Hi @valessiobrito! Can you take a look at it?

**Comment by valessiobrito** [comment]
I could not see this error in my version of Google Chrome 59.0.3071.86 (64 bits, Linux).
We believe that Mapbox is a third-party JavaScript so it can render in different ways for different browsers.
Your screenshot seems to have a logged out version of Mapbox (using Firefox) and a version you also authenticated in Mapbox (using Chorme);
I will create an account in Mapbox to view logged in, and look for some solution.

Thank you for reporting!

**Comment by diraol** [comment]
One important thing to notice is that our map can be rendered in  two different ways. The first one, is by using mapbox-gl (webGL version). If the browser does not support webGL, thus mapbox-gl, then we use the standard javascript mapbox library, which use images (bitmaps) to "render" the map. This is way the screenshots looks differently.

Regarding the bottom elements, we may just have to deal with them (make sure that they are below our own elements.

Regarding the top-left element presented on the second image, this looks like a 'map navigator box' (with zoom features). This one may require some 'javascript setup' for the mapbox-gl library.

Thanks for looking at it @valessiobrito ;)

**Comment by diraol** [comment]
@valessiobrito any news on this topic?

**Comment by valessiobrito** [comment]
I still can't reproduce this error in my Google Chrome for GNU/Linux. My Mapbox is not showing these elements. Did you validate if this problem occurs in more than one browser (Internet Explorer)?

**Comment by cemsbr** [comment]
I can reproduce only the bottom-right corner in Chromium 59.0.3071.115 (Developer Build) while logged in Mapbox. @beraldoleal, I can't assign @valessiobrito because he's not a member yet.

![mapbox](https://user-images.githubusercontent.com/49481/28041165-bbde82be-659e-11e7-96bc-373227808c8f.jpg)

**Comment by valessiobrito** [comment]
A proposal solution for not overlapping mapbox credits.

> diff --git a/web-ui-src/sass/kytos/stylesheets/_terminal.scss b/web-ui-src/sass/kytos/stylesheets/_terminal.scss
> index 2fdffe6..8fbdf89 100644
> --- a/web-ui-src/sass/kytos/stylesheets/_terminal.scss
> +++ b/web-ui-src/sass/kytos/stylesheets/_terminal.scss
> @@ -57,7 +57,7 @@
>          height: 30px;
>  
>    #statusicons {
> \-           background: #111;
> \+           top: -90px;
>             padding-bottom: 10px;
>          }
> 

Result:
![captura de tela de 2017-07-12 05-14-25](https://user-images.githubusercontent.com/310049/28110826-85e4d95a-66c1-11e7-8daa-2a9d31f8123b.png)

@macartur Can you apply this patch to your PR #525 please?
