### ISSUE TITLE
Rethink CoreNapps vs Napps

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#47]
We need to think how to differentiate a normal NApp from a CoreNApp, and how to avoid that a NApp easily became a CoreNApp.

**Comment by cemsbr** [comment]
I believe that no NApp will be required unless a protocol is defined. For instance, of_core is required for the vast majority of OpenFlow NApps, but not useful for other protocols. Thus, I believe we can forget the concept of core NApp for now and specify any dependency in  kytos.json (e.g. of_core).

So, I believe this issue can be solved by removing the KycoCoreNApp class.

**Comment by diraol** [comment]
As we have discussed on the last weeks, we are aborting this concept of "CoreNApp".
