### ISSUE TITLE
install procedure and python package creation is not aligned with pip and setuptools

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#471]
The correct way to deal with the package dependencies is to use install_requires paramenter in setup.py setuptools.setup() call, and the correct way to deal with the setup script dependencies is to use setup_requires parameter. (see https://github.com/kytos/kytos/compare/master...erickvermot:new_setup_no_pip_call)
But, this lead to the setup script being aborted because it is trying to modify files outside the build area (/etc files, etc...):

```
[...]
Searching for kytos-utils>=2017.1b3
Reading https://pypi.python.org/simple/kytos-utils/
Downloading https://pypi.python.org/packages/23/5b/32a2affe4b13f8de90e853066c65f2416f9940c016fbc29875ce173f2fa2/kytos-utils-2017.1b3.tar.gz#md5=67e95a90581693265e5220f0cb3006c4
Best match: kytos-utils 2017.1b3
Processing kytos-utils-2017.1b3.tar.gz
Writing /tmp/easy_install-qfrcwyjg/kytos-utils-2017.1b3/setup.cfg
Running kytos-utils-2017.1b3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-qfrcwyjg/kytos-utils-2017.1b3/egg-dist-tmp-wojx7z76
error: Setup script exited with error: SandboxViolation: mkdir('/etc/skel/kytos/napp-structure/username', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

When reading about this, I have come to many conclusions that I'd like to share here so we can discuss the installation process.

python packages were not meant for applications.

pip and setuptools do not expect things to be installed outside the package in arbitrary locations.

if we do want to distribute kytos as a python package, then all the logic regarding placing /etc/kytos files, and /var/lib/kytos files should be outside setup.py.
Maybe done during the first time kytos is run, or simply checking for them every time and creating them if needed. (erasing /etc/kytos or /var/lib/kytos would not be a problem anymore)
Obviously the logic about the pidfile in /var/run would have to change.

This way we can:
- simply use setup_requires and install_requires to deal with dependencies,
avoid calling pip from within setup (bad practice that may lead to serious problems) and let pip deal with the requirements in its own way.
- make the correct use of requirements.txt.
- not have to worry if setup.py is run in a VENV or not.
- not have to worry about wheels problems that arise when placing files outside the package.
- not have to worry about some other package putting kytos in its install_requirements.
- allow kytos to be installed and run by a regular user.

I'll place some of the links I read with relevant info about the subject.
I'll try to organize it better and update the comment as soon as possible.

**Comment by erickvermot** [comment]
PS: I recommend reading the entire discussion in https://github.com/pypa/pip/issues/2874, as it contains much of the related discussion present in other places.

### about install_requires and setup_requires:

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies
> setuptools supports automatically installing dependencies when a package is installed
The simplest way to include requirement specifiers is to use the install_requires argument to setup().


https://setuptools.readthedocs.io/en/latest/setuptools.html
> setup_requires
A string or list of strings specifying what other distributions need to be present in order for the setup script to run. setuptools will attempt to obtain these (even going so far as to download them using EasyInstall) before processing the rest of the setup script or commands. This argument is needed if you are using distutils extensions as part of your build process; for example, extensions that process setup() arguments and turn them into EGG-INFO metadata files.
(Note: projects listed in setup_requires will NOT be automatically installed on the system where the setup script is being run. They are simply downloaded to the ./.eggs directory if they’re not locally available already. If you want them to be installed, as well as being available when the setup script is run, you should add them to install_requires and setup_requires.)


*related bugs*

setup_requires and install_requires don't play nicely together #209
https://github.com/pypa/setuptools/issues/209


dependencies listed in both setup_requires and install_requires install to temporary .egg dir #391
https://github.com/pypa/setuptools/issues/391


### about requirements.txt

https://packaging.python.org/discussions/install-requires-vs-requirements/
> install_requires
install_requires is a setuptools setup.py keyword that should be used to specify what a project minimally needs to run correctly. When the project is installed by pip, this is the specification that is used to install its dependencies.
It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.
Lastly, it’s important to understand that install_requires is a listing of “Abstract” requirements, i.e just names and version restrictions that don’t determine where the dependencies will be fulfilled from (i.e. from what index or source). The where (i.e. how they are to be made “Concrete”) is to be determined at install time using pip options. [1]
Requirements files
Requirements Files described most simply, are just a list of pip install arguments placed into a file.
Whereas install_requires defines the dependencies for a single project, Requirements Files are often used to define the requirements for a complete python environment.
Whereas install_requires requirements are minimal, requirements files often contain an exhaustive listing of pinned versions for the purpose of achieving repeatable installations of a complete environment.

https://pip.pypa.io/en/stable/user_guide/#requirements-files
> "Requirements files" are files containing a list of items to be installed using pip install like so:
Logically, a Requirements file is just a list of pip install arguments placed in a file. Note that you should not rely on the items in the file being installed by pip in any particular order.
Requirements files are used to hold the result from pip freeze for the purpose of achieving repeatable installations. In this case, your requirement file contains a pinned version of everything that was installed when pip freeze was run.
+++ It's important to be clear that pip determines package dependencies using install_requires metadata, not by discovering requirements.txt files embedded in projects.



### about pip call:

Create a supported "high level" programmatic API for pip #3121
https://github.com/pypa/pip/issues/3121


https://stackoverflow.com/questions/12937533/use-pip-install-uninstall-inside-a-python-script
> This is a comment to this post that didn't fit in the space allotted to comments.
Note that the use case of installing a package can arise inside setup.py itself. For example, generating ply parser tables and storing them to disk. These tables must be generated before setuptools.setup runs, because they have to be copied to site_packages, together with the package that is being installed.
There does exist the setup_requires option of setuptools.setup, however that does not install the packages.
So a dependency that is required both for the installation process and for the installed package will not be installed this way.
Placing such a dependency inside install_requires does not always work as expected. Even if it worked, one would have to pass some function to setuptools.setup, to be run between installation of dependencies in setup_requires and installation of the package itself. This approach is nested, and thus against PEP 20.
So the two flat approaches that remain, are:
    run setup.py twice, either automatically (preferred), or manually (by notifying the user that the tables failed to build prior to setuptools.setup.
    first call pip (or some other equivalent solution), in order to install the required dependencies. Then proceed with building the tables (or whatever pre-installation task is necessary), and call setuptools.setup last.
Personally, I prefer No.2, because No.2 can be confusing to a user observing the console output during installation, unless they already know the intent of calling setuptools.setup twice.
Besides, whatever rights are needed for installation (e.g., root, if so desired), are certainly present when setup.py is run (and exactly then). So setup.py could be considered as the "canonical" use case for this type of action.


pip -r double installs if called also from within setup.py #2745
https://github.com/pypa/pip/issues/2745
> Build dependencies should be declared in setup_requires. I realise that that has some poor behaviours today, but it is the defined interface - and I'm working up the stack to be able to make that declarative soon I hope.



### About writing data file to arbitrary location on a user's machine, and about how to access config files inside the package: (can be used during application execution, or be copied to the desired location like /etc in the first run)

Python setuptools: how to include a config file for distribution into <prefix>/etc
https://stackoverflow.com/questions/10456279/python-setuptools-how-to-include-a-config-file-for-distribution-into-prefix-e
> you can't actually install data files to some arbitrary location on a user's machine


http://peak.telecommunity.com/DevCenter/setuptools#non-package-data-files
> Non-Package Data Files
The distutils normally install general "data files" to a platform-specific location (e.g. /usr/share). This feature intended to be used for things like documentation, example configuration files, and the like. setuptools does not install these data files in a separate location, however. They are bundled inside the egg file or directory, alongside the Python modules and packages. The data files can also be accessed using the Resource Management API, by specifying a Requirement instead of a package name:
from pkg_resources import Requirement, resource_filename
filename = resource_filename(Requirement.parse("MyProject"),"sample.conf")
The above code will obtain the filename of the "sample.conf" file in the data root of the "MyProject" distribution.
Note, by the way, that this encapsulation of data files means that you can't actually install data files to some arbitrary location on a user's machine; this is a feature, not a bug. You can always include a script in your distribution that extracts and copies your the documentation or data files to a user-specified location, at their discretion. If you put related data files in a single directory, you can use resource_filename() with the directory name to get a filesystem directory that then can be copied with the shutil module. (Even if your package is installed as a zipfile, calling resource_filename() on a directory will return an actual filesystem directory, whose contents will be that entire subtree of your distribution.)
(Of course, if you're writing a new package, you can just as easily place your data files or directories inside one of your packages, rather than using the distutils' approach. However, if you're updating an existing application, it may be simpler not to change the way it currently specifies these data files.)


http://peak.telecommunity.com/DevCenter/PythonEggs#resource-management
> Accessing Package Resources
Many modern Python packages depend on "resources" (data files) that are included with the package, typically placed within the package's subdirectory in a normal installation. Usually, such packages manipulate their modules' __file__ or __path__ attributes in order to locate and read these resources. For example, suppose that a module needs to access a "foo.config" file that's in its package directory. It might do something like:
foo_config = open(os.path.join(os.path.dirname(__file__),'foo.conf').read()
However, when code like this is packed inside a zipfile, it can no longer assume that __file__ or __path__ contain filenames or directory names, and so it will fail.
Packages that access resource files, and want to be usable inside a zipfile (such as a .egg file), then, must use the PEP 302 get_data() extension (see under "Optional Extensions to the Importer Protocol") before falling back to direct __file__ access.
Using this protocol can be complex, however, so the egg runtime system offers a convenient resource management API as an alternative. Here's our "foo_config" example, rewritten to use the pkg_resources API:
from pkg_resources import resource_string
foo_config = resource_string(__name__, 'foo.conf')
Instead of manipulating __file__, you simply pass a module name or package name to resource_string, resource_stream, or resource_filename, along with the name of the resource. Normally, you should try to use resource_string or resource_stream, unless you are interfacing with code you don't control (especially C code) that absolutely must have a filename. The reason is that if you ask for a filename, and your package is packed into a zipfile, then the resource must be extracted to a temporary directory, which is a more costly operation than just returning a string or file-like object.

https://www.python.org/dev/peps/pep-0302/
> get_data()


### about data_files:

setuptools sdist ignore data_files
https://stackoverflow.com/questions/38117149/setuptools-sdist-ignore-data-files

https://packaging.python.org/tutorials/distributing-packages/#data-files
data_files
data_files=[('my_data', ['data/data_file'])],
Although configuring package_data is sufficient for most needs, in some cases you may need to place data files outside of your packages. The data_files directive allows you to do that.
Each (directory, files) pair in the sequence specifies the installation directory and the files to install there. If directory is a relative path, it is interpreted relative to the installation prefix (Python’s sys.prefix for pure-Python distributions, sys.exec_prefix for distributions that contain extension modules). Each file name in files is interpreted relative to the setup.py script at the top of the project source distribution.
For more information see the distutils section on Installing Additional Files.
Note
setuptools allows absolute “data_files” paths, and pip honors them as absolute, when installing from sdist. This is not true when installing from wheel distributions. Wheels don’t support absolute paths, and they end up being installed relative to “site-packages”. For discussion see wheel Issue #92. 


bdist_wheel makes absolute data_files relative to site-packages
https://bitbucket.org/pypa/wheel/issues/92


distutils allows additional files with absolute path, but not setuptools
https://docs.python.org/3.6/distutils/setupscript.html#installing-additional-files


data_files behaves differently for pip, setuptools, and wheel
https://github.com/pypa/setuptools/issues/460
https://github.com/pypa/pip/issues/2874#issuecomment-109429489
https://github.com/pypa/pip/issues/2874#issuecomment-109444845
They are writing out files like /etc/init/my-service or similar "I'm using Python packages like they were OS packages" situations.
The second situation is one where I think there is a valid use case here, but I don't think the valid use case involves being able to write to arbitrary paths anywhere on the system. If someone installs your project into a virtual environment, you shouldn't be able to touch files outside of that virtual environment. The fact it is technically possible today because of the nature of setup.py does not mean that it is a good thing or that we're going to wish to support it moving into the future. In this regard, I think rooting data_files in sys.prefix (or some other variable that would scope it to the system in a system install, and the virtualenv root otherwise) is the right thing here and that setuptools got it wrong. Most likely the only reason setuptools does what it did is because of egg installs (another feature that folks are moving away from).

https://github.com/pypa/pip/issues/2874#issuecomment-109482660
The ability to stick files in arbitrary locations is a misfeature, and supporting features that make that possible isn't something I'm interested in doing. Full stop. All files should be scoped to be within the scope of the environment they are being installed into.
You've correctly pointed out that people can just do it by throwing some arbitrary Python into their setup.py, of course they can do that, but it has a few major differences:

-It's more obviously the wrong thing to do rather than just subtly the wrong thing to do.
-If they do that, that's a short term "fix" anyways as we move away from setup.py and towards declarative packages.
-It's not a "feature" of the packaging toolchain, just a side effect of the fact that setup.py is executable.

<___>   It does seem super obvious that projects in virtualenvs shouldn't be able to write outside their virtualenv
<___>   It hadn't even really occurred to me that they could
<___>   Or that a developer would do that

**Comment by cemsbr** [comment]
Not writing files outside the build environment would make things much easier for us. I think this is the right way to do it, but we should discuss about not impacting usability. A suggestion: have a cli command to generate the config files and (writing them on first run or using our default files until new ones are generated).

**Comment by hdiogenes** [comment]
Superseded by #1042.
