### ISSUE TITLE
NApps are not (un)loaded after disabled/enabled

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#476]
We are going to change the architecture for chico release. In bethania, we we should solve this with as less impact as possible.

A new class should be instantiated as a thread to listen for links created and removed in the napps-enabled folder. Existent controller methods should be used to load/unload these napps.

**Comment by renanrodrigo** [comment]
@cemsbr , is this related to kytos/kytos-utils#92 ? Seems like the same 'less impact solution' can take care of both. Am I wrong?

**Comment by cemsbr** [comment]
Yes, thanks, this is a duplicate. I'm closing the other one because this issue is being tracked with assignee, lables, milestone, ...
