### ISSUE TITLE
[web-ui] Terminal pannel - Cursor animation uses too much CPU

### ISSUE THREAD

**Issue by rmotitsuki** [kytos/kytos#489]
The flashing cursor in the Terminal panel header uses too much CPU to render the animation easing. Probably the reason is the alpha/opacity manipulation.
Removing the class="ti-cursor" element directly from the HTML page drops the browser CPU usage from 100% to 6%.

Tested using last Chrome version in Ubuntu.

**Comment by diraol** [comment]
@valessiobrito Can you take a look at it?

**Comment by valessiobrito** [comment]
@diraol there is no such class 'ti-cursor' in the current version, maybe it is referring to an old version or another repository (fork). 
@rmotitsuki could you please tell me more details?

**Comment by rmotitsuki** [comment]
@valessiobrito  I think that the 'ti-cursor' class is generated by the typeid js library. I tracked it down until command the `$('.terminal-status-bar span').typeIt({` in [kytos-terminal.js:88](https://github.com/kytos/kytos/blob/master/kytos/web-ui/static/js/kytos-terminal.js#L88)
It seems that the typeid terminal is using the default values to the blinking animation.

**Comment by cemsbr** [comment]
@valessiobrito, this is about the current UI, in master branch.

**Comment by beraldoleal** [comment]
@valessiobrito let fix this only on new interface.

**Comment by beraldoleal** [comment]
This is fixed, but anyway... with new new ui this will be completely new.
