### ISSUE TITLE
Define the internal handshake workflow.

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#49]
We need to discuss and define the internal handshake workflow process of `kyco`.

Things to be considered:
- When is the KycoSwitch instance created?
- Until the `FeaturesReply` message we do not have a `datapath_id` (`dpid`) to be used as the switch identifier.
  - This means that the `Hello` message does not contain the necessary data for the Switch identification, it  only contains the `(ip, port)` information (`connection_id`).
- Will we allow the apps to see `KycoMessage*` events that does not contains the `dpid`?
  - If not, then we can't allow apps to access the `Hello` (in and out) messagens, and also the first `FeatureRequest` and the first `FeaturesReply` messages)
- For now, because we create the `KycoSwitch` instance while handling the `FeaturesReply` message, both the `Hello` and `FeaturesReply` message handlers are inside the controller instead of being on an KycoApp, since they need to create and save the switch on the controller.
- How are we going to 'control' the 'state' of the handshake process? How to avoid exchanging messages prior to the end of the handshake?
  - A related topic to this item is where do we keep track of messages `xid` to check if a received answer have the same `xid` as the sent request. (For example on `FeaturesRequest` <-> `FeaturesReply`)

**Comment by diraol** [comment]
https://github.com/kytos/kyco/wiki/Blueprints-handshake

**Comment by diraol** [comment]
http://flowgrammable.org/sdn/openflow/state-machine/

**Comment by beraldoleal** [comment]
@diraol all your description looks like is already on EP007, right ? If yes, let's close this and discuss this proposal on #302.

**Comment by diraol** [comment]
@beraldoleal sure we can close it! =)
If anything is not over there, we can just come back to this issue in order to get some references ;)
