### ISSUE TITLE
Wildcards in Flow class

### ISSUE THREAD

**Issue by ajoaoff** [kytos/kytos#521]
In our application, it will be necessary to match a packet against the flow in the control plane, for Interdomain tracepath. To do that, wildcards are necessary, but they are not available in [Flow](https://github.com/kytos/kytos/blob/master/kytos/core/flow.py#L11) class.

**Comment by diraol** [comment]
@ajoaoff looking again to this issue, and also to #517 and #518, one thing has got my attention.

You are using the Flow class defined inside kytos core. But, as you are developing a NApp, it is better if you use the python-openflow library to build and 'use' OpenFlow strucutres.
As an example, you can use the classes [`FlowMod`](https://docs.kytos.io/python-openflow/pyof.v0x01.controller2switch/#pyof.v0x01.controller2switch.flow_mod.FlowMod) and [`Match`](https://docs.kytos.io/python-openflow/pyof.v0x01.common/#pyof.v0x01.common.flow_match.Match), which were implemented following the Openflow Specification.

Take a look at them and see if they fit your needs. =)

#edited

**Comment by ajoaoff** [comment]
@diraol maybe not the best option. 
For example, we need to use the flows currently installed at the switches. The NApp kytos/core already uses FlowStats to retrieve the flows, but stores than using the Flow class. If I directly use python-openflow library, I would have to retrieve the flows again, and I don't know if it is a good idea.

**Comment by cemsbr** [comment]
@macartur, could you please add the wildcard attribute as you did in the issues referenced by Diego? Because wildcards are automatically managed by pyof, you only have to add the wildcard when converting **to** JSON.

**Comment by diraol** [comment]
Fixed on #511 .

@ajoaoff could you please test it to see if it is working ok?
Thanks!

**Comment by cemsbr** [comment]
Without comments, I'm assuming it's solved. If not, please, reopen.
