### ISSUE TITLE
Default `daemon` value in configuration is being ignored

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos#529]
As can be seen in [Kytos Admin Guide](https://github.com/kytos/kytos/blob/master/docs/administrator/configuration.rst) refering to [Kytos configuration file](https://github.com/kytos/kytos/blob/master/etc/kytos/kytos.conf.template), the `daemon` parameter is set to `False` by default, leading to interactive mode. However, Kytos does start as a daemon by default - the interactive mode requires the `-f` command line parameter.

Also, `daemon=False` is inside `[daemon]`. Is this expected somehow?

**Comment by diraol** [comment]
@beraldoleal what should be the default behaviour? As `daemon` or as `foregroud` application?

**Comment by hdiogenes** [comment]
Still valid. Two issues here:
1. The configuration parameter in the file is being ignored (comes as `False` but works as `True`)
1. I think the default should be `daemon=True`, so the default file should be updated to reflect this (and whatever is there should be respected if no command-line flag says the opposite).
