### ISSUE TITLE
Send data to switch, if possible, should be uniform

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#53]
`switch.send()` is better than `controller.send_to_switch` and `controller.send_to_connection()`.

I will accept PR #51, but I think that we should rethink this, to make it clean.

**Comment by diraol** [comment]
There are two things that we may consider.

The first one is that we have two different 'stages' of 'send'. Before and after the handshake.

Before the handshake we do not have a `switch` object, so 'switch.send()' would not be possible. At this moment we just have a `connection` (that is handled by the `controller` itself).

Considering only the moment after the instantiation of  the `switch` object, I think that is not a good idea to let the responsibility of finding the correct `switch` before sending the message to each method that wants to send a message to the switches. I think that it is better to centralize this process (on the `Controller` or on a `KycoSwitchManager`).

**Comment by beraldoleal** [comment]
The PR #64 fixes part of this problem. Will need to think in a way to put everything inside a switch class.
