### ISSUE TITLE
__event.set() causes re-enabled NApps's loops to fail.

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos#532]
When a NApp is disabled, a call to `self.__event.set()` is executed. If it is enabled again without restarting the controller, `self.__event.is_set()` keeps returning `True`, preventing the `execute` method to loop when intended.

A call to `self.__event.clear()` is needed prior to execution to fix this.

**Comment by diraol** [comment]
I've made some comments on the Pull Request ( #533 ) about this issue.
