### ISSUE TITLE
Documentation updates - How to Contribute

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#535]
- [x] Move 'contributing' (How to contribute) from `kytos/documentation` to here;
- [x] Review and improve 'contributing';
- [ ] Propose an `Issue template`[1], [2]
- [ ] Propose an `Pull Request template`[1]. [2]
- [x] Move 'Submit an issue' from 'contributing' to 'get help' [under kytos/kytos]

[1] https://help.github.com/articles/helping-people-contribute-to-your-project/
[2] https://github.com/stevemao/github-issue-templates

**Comment by cemsbr** [comment]
@erickvermot, if you can't do all tasks, it's OK to do some of them.

**Comment by cemsbr** [comment]
Moved unfinished items to kytos/kytos#595.
