### ISSUE TITLE
Documentation Updates - Hacking/Dev guide

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#536]
Merge `hacking` (it is under kytos/documentation repo) with the `developer guide`.

**Comment by erickvermot** [comment]
@diraol there is no ``hacking`` in documentation repo, do you mean hacking in the kytos/docs ?

**Comment by erickvermot** [comment]
I'm unassigning myself because there seems to be nothing more useful from hacking.rst (it was written in the very early stages of dev), and the devguide structure is not decided yet.
Work can be continued once the structure is established.
