### ISSUE TITLE
DevGuide - Python Openflow Section

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#538]
On the `DevGuide` we need to have a "section" (page) `python-openflow`. On this "section" we need, at least, the following topics to be covered:
 - Basic lib organization;
 - How to use the python-openflow library;
   - pyof Objects;
   - packing;
   - unpacking;
 - Difference among "structs" and "messages";
 - How to code a new "struct" (on an existing pyof version);
 - How to code a new "message" (on an existing pyof version);
 - How to start a new "pyof version";
 - etc.

All of this topics must cover also how to implement the necessary tests to assure the qualitfy of the proposed code.

Suggestions to improve this section are welcome. What is missing here?

**Comment by erickvermot** [comment]
@diraol, @cemsbr So python-openflow development section will be inside kytos docs devguide ?

**Comment by erickvermot** [comment]
since python-openflow is a different repo, it seems to me it makes more sense to be inside the python-openflow repo...
Furthermore, much of the "How to code a new \*" is already inside the docstrings of the classes, like GenericStruct and GenericMessage

**Comment by diraol** [comment]
@erickvermot for now we are concentrating all main documentation files from Kytos SDN Platform under 'kytos/docs'. Eventually, on the future, we may move this python-openflow documentation to pyof repository (under docs), 

So, doing it here inside a specific file will make it easy to move on the future.

Regarding the docstrings, yes, we do have some information about that topics over there, but here we can do a much better work, writing more texts, giving more examples and even using some images if needed. On the documentation we must master our explanations as much as we can. We want our (dev) users to reach this pages before they really need to go to the source code.

That does not mean that our source code docstrings doesn't need to be excelent, since they are used both on the specific "project API" documentation page and also on the command line.

**Comment by erickvermot** [comment]
I have implemented 2 docs:

one with the current behavior of pyof:
  https://github.com/erickvermot/kytos/tree/docs_python_openflow

one with the behavior of pyof if some of the proposed mods, PRs, and open issues are accepted:
  https://github.com/erickvermot/kytos/compare/docs_python_openflow...erickvermot:docs_python_openflow_new_method

please take a look and let me know when I can open a PR.

**Comment by erickvermot** [comment]
@cemsbr I did the changes you asked in your comments in the branch.
But are you sure it is easier or faster to make 17 comments about single character changes than change them while you review?

**Comment by cemsbr** [comment]
It is not easier neither faster, but I'm thinking in the long run. By fixing all these simple errors, you'll make less errors next time. Soon, there will be nothing or only a few comments in a review.

**Comment by erickvermot** [comment]
that is not the case...
