### ISSUE TITLE
Create @rest decorator

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#561]
Now that `@rest` is implemented and we have the `/api/user/napp/` prefix, how should we deal with legacy NApp's `self.controller.register_rest_endpoint` (shortcut for `self.controller.api_server.register_rest_endpoint`)?

One solution is removing the method and force @rest decorator. Another possibility is to mark `register_rest_endpoint` as deprecated and generate a warning, letting the user override any `/api/user/napp/` endpoint. A third option is the second one + checking and forbidding endpoint overriding.

IMHO, we should simply mark `register_rest_endpoint` as deprecated. Much probably no user has used `/api/another_user/another_napp` as URL, so we shouldn't spend time coding this rare edge case. Besides, it will be impossible to override endpoints of another NApp after we decentralize NApps by using a broker/dealer + an HTTP API NApp.

**Comment by diraol** [comment]
@cemsbr I like the deprecation warning approach, but I can forsee a big problem with it.

As far as I understood, we are going to change the `baseurl` for our api, from `host:port/kytos` to `host:port/api`. Doing so, if we keep using the `register_rest_endpoint` as it was before, prefixing the endpoint with `/kytos/user/napp_name/`, then this URL will probably not be accessible anymore, or we are going to have an inconsistent REST API. Considering that, may be we may just move towards using only the `@rest` decorator and ask all NApp developers to make this small change (and they will also need to fix any call the old `baseurl`).

Or am I wrong?

**Comment by cemsbr** [comment]
Maybe I'm too concerned about users, but a middle path would be marking it as deprecated, logging an error and not starting the endpoint.

**Comment by diraol** [comment]
@cemsbr my point is that usually the users would create the endpoint for themselves, which means that they may be using it (on the NApp itself, on another NApp or on some GUI). By not registering the endpoint, they will break anyway right? Then the users won't be covered by a backwards compatible change right?

**Comment by beraldoleal** [comment]
@cemsbr let's keep the method `register_rest_endpoint` and add a deprecated warning when someone call it.

@diraol regarding changing the prefix, yes you are right. But is ok for them to change any prefix on their code.
