### ISSUE TITLE
Close connections when shutting down

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos#578]
When kytos shuts down, it waits for all the switches' connections to timeout before leaving. In real scenarios it may take some time.

**Comment by hdiogenes** [comment]
It looks that there's a missing socket.shutdown() before .close(). From [the docs](https://docs.python.org/3/library/socket.html#socket.socket.close):

> Note: close() releases the resource associated with a connection but does not necessarily close the connection immediately. If you want to close the connection in a timely fashion, call shutdown() before close().

**Comment by beraldoleal** [comment]
@hdiogenes feel free to make a PR. It will be more than welcome.

**Comment by viniarck** [comment]
I've talked to @hdiogenes about this issue, and this issue hasn't shown up anymore since asyncio has been part of the core. I'll close this issue.
