### ISSUE TITLE
Install Kytos dependencies from master branch

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#598]
Currently, the dev install procedure installs, for example, kytos-utils from pypi, which quickly becomes obsolete for development. If instead we install from GitHub, it will get the latest commit. We have to be careful with CI that restricts downloads.

This issue was created based on kytos/of_lldp#4.

**Comment by hdiogenes** [comment]
python-openflow and kytos-utils are being installed from github on dev requirements - https://github.com/kytos/kytos/blob/master/requirements/dev.txt#L8
