### ISSUE TITLE
The RESTful API in legacy/of_stats should not be decorated as @staticmethod

### ISSUE THREAD

**Issue by xiangq27** [kytos/kytos#602]
I was following the RESTful API tutorial at this link (https://tutorials.kytos.io/napps/restful_statistics/) and couldn't make it work. So I look into the source code of legacy/of_stats at (https://github.com/kytos/legacy/blob/master/napps/kytos/of_stats/main.py). I notice that this napp only works if I change the following snippet:

    @rest('<dpid>/flows')
    @staticmethod
    def get_flow_list(dpid):

to 

    @rest('<dpid>/flows')
    def get_flow_list(self, dpid):

The environment I was working on is the virtualenv provided by pythong3.6, as required in the tutorial. 

Can anyone look into this problem and clarify to us what would be the potential reason? This would be very helpful for futher Kytos users and developers. Thank you.

**Comment by diraol** [comment]
Hi @xiangq27 the PR #600 just fix the issue #599, which is what is causing this problem you are reporting.

So, probably if you update your `Kytos` to the current version on our repo master branch you will be good to go ;)

Try it and report us back, please.

Cheers!

**Comment by cemsbr** [comment]
If the problem persists, please, reopen.

**Comment by xiangq27** [comment]
It is fixed in the latest Kytos. Thank you very much.
