### ISSUE TITLE
Lint and fix "bin" directory

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#613]
- [ ] Add bin directory to the list of files to be linted (setup.py)
- [x] Fix linter errors

**Comment by hdiogenes** [comment]
Partially done on #699, when almost all the code in /bin was moved to /core.

**Comment by hdiogenes** [comment]
Like I said in the previous comment, `bin/kytosd` content was moved to the `kytos.core.kytosd` module, which forced all the lint issues to be fixed and got the `bin/kytosd` file from ~200 to ~20 lines, which do not produce lint errors anymore, so I think this issue can be closed.
