### ISSUE TITLE
Use proper mime type in REST replies

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#636]
In all NApps but of_stats, there might be JSON content being delivered with the default 'text/html' mime type. It should be changed to `application/json` (i.e. https://github.com/kytos/of_stats/blob/e2a73e11b082e930a63c858ac2a474b6905d2c34/stats_api.py#L91).

**Comment by macartur** [comment]
All NApps are:
-  [x] kytos/of_stats
-  [x] kytos/status
-  [x] kytos/flow_manager
-  [x] kytos/topology
-  [x] kytos/pathfinder

**Comment by macartur** [comment]
All NApps are already fixed.
