### ISSUE TITLE
Remove dummy kytos/core/daemon.py

### ISSUE THREAD

**Issue by hdiogenes** [kytos/kytos#679]
It's a dummy file, completely [commented out](https://github.com/kytos/kytos/blob/ff4c1d65edfbda09d9a1d1318bcc6f4313cc5da7/kytos/core/daemon.py). Is there any reason for it to still exist in the codebase?

**Comment by beraldoleal** [comment]
This is a working in progress and was started a long time ago. Probably we will reintroduce the code again soon.

**Comment by hdiogenes** [comment]
My vote is for the code to live on its own WIP branch and be removed from master until it works, but if you prefer we can just leave it as it is and close this ticket.

**Comment by beraldoleal** [comment]
We decided to use our master branch as a "wip branch". But yes, thanks for taking a look on this.
