### ISSUE TITLE
raw_event_handler() docstring is outdated

### ISSUE THREAD

**Issue by hdiogenes** [kytos/kytos#681]
kytos.core.Controller.[raw_event_handler() docstring](https://github.com/kytos/kytos/blob/master/kytos/core/controller.py#L358) says it verifies something that the code doesn't verify:

>        It also verify if there is a switch instantiated on that connection_id
>        `(ip, port)`. If a switch was found, then the `connection_id` attribute
>        is set to `None` and the `dpid` is replaced with the switch dpid.

This is the full method code:

```
    def raw_event_handler(self):
        self.log.info("Raw Event Handler started")
        while True:
            event = self.buffers.raw.get()
            self.notify_listeners(event)
            self.log.debug("Raw Event handler called")

            if event.name == "kytos/core.shutdown":
                self.log.debug("RawEvent handler stopped")
                break
```

**Comment by beraldoleal** [comment]
@renanrodrigo @macartur did you guys remember where this was copied ?

**Comment by hdiogenes** [comment]
@beraldoleal, it looks like this code was removed by you in a refactoring ( https://github.com/kytos/kytos/commit/f9dc5b55738212811ca63fbcb046ecc302e9e31e#diff-8357fb77d6f904bee089b1d1cf641b52L217 ), so I think you should review it and decide if any of that behavior must be restored, or if we should just remove the docstring.

**Comment by beraldoleal** [comment]
For me, makes no sense to change the dpid and connection_id here. So, can you please remove the docstring and close this issue ?

**Comment by hdiogenes** [comment]
@beraldoleal, I can't commit directly on master because it is protected, so I made a PR.
