### ISSUE TITLE
Remove diraol/watchdog dependency

### ISSUE THREAD

**Issue by hdiogenes** [kytos/kytos#702]
setup.py and .scrutinizer.yml are pointing to an external fork, that must be forked locally on the Kytos project or removed altogether from the dependencies.

Check if the Python egg has to be created manually or not.

It also has to be removed from two NApps' .scrutinizer.yml files: `mef_eline` and `status`.

**Comment by hdiogenes** [comment]
All the fork does is remove the PyYAML dependency, but it looks like pip is ignoring the fork and downloading the official version. A `pip install -v --no-cache-dir kytos` yields the following:

```
    ...
    Collecting PyYAML>=3.10 (from watchdog->-r requirements/run.in (line 15))
    ...
    Installing collected packages: PyYAML, watchdog
    Successfully installed PyYAML-3.12 watchdog-0.8.3
    ...
 ```

**Comment by hdiogenes** [comment]
No egg needs to be created, as the URL just points to the zip file download from github:
```
      dependency_links=[
          'https://github.com/diraol/watchdog/archive/master.zip#egg=watchdog'
      ],
```

**Comment by beraldoleal** [comment]
If we are not using, we can remove. Not a problem.

**Comment by hdiogenes** [comment]
It had something to do with a missing wheel (see 48d8c5b01e7c91610ce1feac92f8d6a57cc3f1ff), but I don't know what the original problem was or if it is really solved by now.
