### ISSUE TITLE
 Create initscript for systemd

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#71]
We need to know what is mandatory for debian. Only systemd ? Or do we need init v ? Upstart ?

**Comment by abaruchi** [comment]
Good documentation to start:
https://fedoramagazine.org/what-is-an-init-system/

**Comment by abaruchi** [comment]
It is under discussion with Paulo. According to the available documentation, it is necessary only to create a UNIT file, which describes several information about the daemon (such as start, stop and reload command, documentation, dependencies, order of execution, so on..). 

The discussion available in link below says that rc.X scripts are used by a program called `systemd-sysv-generator` to create a unit file to systemd. So, if it is true, there is no need to create a script (at least for this release) to support others system startups mechanisms.
Link:
http://unix.stackexchange.com/questions/233468/how-does-systemd-use-etc-init-d-scripts

**Comment by beraldoleal** [comment]
".... systemd was included in Debian wheezy as a technology preview.... 
.... This will install the systemd packages but will not configure systemd as your init system. "

First we have to make sure that systemd is default on debian/ubuntu (or has plans to). Otherwise we should focus on debian/ubuntu default.

https://wiki.debian.org/systemd

**Comment by beraldoleal** [comment]
@abaruchi, please submit a PR with your systemd. And in parallel we do this investigation about what is the used on debian/ubuntu.

Also we need to check on #9 in order to this init script work properly.
