### ISSUE TITLE
Travis-CI adjustments and compatibilization

### ISSUE THREAD

**Issue by diraol** [kytos/kytos#74]
On the commit 5798257 we have made some adjustments to handle tests on TRAVIS-CI environment.

The question is:
The `kyco-core-napps` dependency 'install' the core napps into a folder to be loaded by `Kyco`. On a production install, the default folder would be `/var/lib/kyco/napps`. But, on a dev or test environment without being a system installation, the "current user" can't install the core napps on that folder.

So, the solution is that if we are on a `Virtual Environment`, then we install this `var/lib/kyco/napps` dir under the `$VIRTUAL_ENV` folder.

On the TRAVIS-CI environment we have faced some strange behaviours regarding this install process, as it can be seen at:
- Build 41 https://travis-ci.org/kytos/kyco/builds/156290287
- Build 42 https://travis-ci.org/kytos/kyco/builds/156293229
- Build 43 https://travis-ci.org/kytos/kyco/builds/156295041
- Build 44 https://travis-ci.org/kytos/kyco/builds/156298829
- Build 45 https://travis-ci.org/kytos/kyco/builds/156299775
- Build 46 https://travis-ci.org/kytos/kyco/builds/156300527
- Build 47 https://travis-ci.org/kytos/kyco/builds/156304330
- Build 48 https://travis-ci.org/kytos/kyco/builds/156305963
- Build 49 https://travis-ci.org/kytos/kyco/builds/156499002
- Build 50 https://travis-ci.org/kytos/kyco/builds/156517281
- Build 51 https://travis-ci.org/kytos/kyco/builds/156540584
- Build 52 https://travis-ci.org/kytos/kyco/builds/156560445
- Build 53 https://travis-ci.org/kytos/kyco/builds/156561584

So, to fix it we have made a workaround on kyco tests to accommodate this environment, as it can be seen here:
https://github.com/kytos/kyco/pull/73/files#diff-581da0faab9db3e01aee423c7f8cf4fdR19

On the future we should look for a better way to handle it.

**Comment by cemsbr** [comment]
Done. All Travis workarounds were removed and our projects are installed directly from GitHub develop branches by pip
