### ISSUE TITLE
Couldn't get port OFPP_LOCAL port "4294967294" speed

### ISSUE THREAD

**Issue by viniarck** [kytos/kytos#754]
I just realized that the OFPP_LOCAL interfaces have a speed of None, which is resulting in an warning every time the user get the information about the topology. This is the warning:

```
2018-06-21 07:54:14,826 - WARNING [kytos.core.interface] (Thread-2331) Couldn't get port 4294967294 speed, sw 00:...:03, feats 0
```

The warning comes from this line https://github.com/kytos/kytos/blob/master/kytos/core/interface.py#L278. By analyzing the message on wireshark on OvS implementation, OFPP_LOCAL should have the speed 0. So, I think we should probably patch this port to return 0 instead of None and as a result the warning won't show up anymore. What do you think?

This patch fixes the issue:

```
diff --git a/kytos/core/interface.py b/kytos/core/interface.py
index fd8aede..8d02473 100644
--- a/kytos/core/interface.py
+++ b/kytos/core/interface.py
@@ -5,6 +5,8 @@ from enum import IntEnum

 from pyof.v0x01.common.phy_port import PortFeatures as PortFeatures01
 from pyof.v0x04.common.port import PortFeatures as PortFeatures04
+from pyof.v0x01.common.phy_port import Port as PortNo01
+from pyof.v0x04.common.port import PortNo as PortNo04

 from kytos.core.common import GenericEntity
 from kytos.core.helpers import now
@@ -237,6 +239,12 @@ class Interface(GenericEntity):  # pylint: disable=too-many-instance-attributes
         """
         if self._custom_speed is not None:
             return self._custom_speed
+        if self._is_v0x04():
+            if self.port_number == PortNo04.OFPP_LOCAL:
+                return 0
+        else:
+            if self.port_number == PortNo01.OFPP_LOCAL:
+                return 0
         return self.get_of_features_speed()

```

To reproduce, you have to trigger this function, for example by getting this endpoint: 

```curl -X GET http://localhost:8181/api/kytos/topology/v3/switches```

**Comment by viniarck** [comment]
@beraldoleal @macartur @hdiogenes when you have the chance to read this issue, let me know if you have a better idea to handle this (I'll wait until them before opening a PR). The impact is not major, but it's annoying to see this warning message showing up every time.

**Comment by beraldoleal** [comment]
@viniarck , Sorry for late reply. If the solution for return 0 affects only this high number port, I'm ok with it.

The problem to look at is when the interface is 100Gbps and OF1.0 do not support this kind of speed. I'm not sure if this change will affect this too.
