### ISSUE TITLE
Discuss how to "centralize" NApps config files in /etc/kytos/

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#793]
/etc/kytos/ or something more appropriate.

**Comment by hdiogenes** [comment]
Currently we have the following napps using individual `settings.py` files for configurations:

* [topology](https://github.com/kytos/topology/blob/master/settings.py)
* [mef_eline](https://github.com/kytos/mef_eline/blob/master/settings.py)
* [pathfinder](https://github.com/kytos/pathfinder/blob/master/settings.py)
* [flow_manager](https://github.com/kytos/flow_manager/blob/master/settings.py)
* [status](https://github.com/kytos/status/blob/master/settings.py)
* [storehouse](https://github.com/kytos/storehouse/blob/master/settings.py)
* [of_lldp](https://github.com/kytos/of_lldp/blob/master/settings.py)
* [of_stats](https://github.com/kytos/of_stats/blob/master/settings.py)
* [of_l2ls](https://github.com/kytos/of_l2ls/blob/master/settings.py)
* [of_core](https://github.com/kytos/of_core/blob/master/settings.py)

**Comment by hdiogenes** [comment]
For example, link `/etc/kytos/napps/kytos/of_core/settings.py` to `/var/lib/kytos/.../of_core/settings.py`.

**Comment by hdiogenes** [comment]
We can implement the linking of settings.py on NApp install/uninstall, or when loading a NApp (to cover the case of a NApp that didn't have a settings.py on an older version starting to have it on a new version.)

**Comment by hdiogenes** [comment]
The new blueprint created in #959 (data and settings persistence) can be a solution to this.

**Comment by hdiogenes** [comment]
Discussion turned into a blueprint: [EP020](/kytos/kytos/blob/master/docs/blueprints/EP020.rst)
