### ISSUE TITLE
Document the backup process in Kytos Admin Guide

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#794]
We need the instructions in order to backup kytos config files + objects on storehouse.

**Comment by hdiogenes** [comment]
The most basic backup is already documented:
`tar cvfz ~/kytos-backup.tar.gz /etc/kytos /var/lib/kytos`

How we can improve it:
- Add datetime and kytos version to the filename
- Save a text file with all the enabled/disabled napps + versions (`kytos napps list` output)

Also, if using storehouse, we need to backup its directory. Maybe we'll need a kytos command just to output its `CUSTOM_DESTINATION_PATH` (default /var/tmp/) [configuration](https://github.com/kytos/storehouse/blob/master/settings.py).

**Comment by hdiogenes** [comment]
I've created #825 to automate the process that was documented here.
