### ISSUE TITLE
Review constants vs confi variables

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#80]
Today there is a lot of constants inside `kyco/constants.py`. Some of them should be config options or a specific app config option. We need to review this.

**Comment by macartur** [comment]
Today there are 3 constants in kytos/core/constants.py. So, I guess we can close this issue.

**Comment by hdiogenes** [comment]
Only 2 of those 3 are being used - 'POOLING_TIME' isn't being used anywhere.

**Comment by beraldoleal** [comment]
Good, @hdiogenes. If POOLING_TIME is not used, please send a PR to remove it.
