### ISSUE TITLE
doc: Fix sections titles responsivity

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#801]

**Comment by valessiobrito** [comment]
Please, could you send some print to Issue. I could not identify.

![responsive-title](https://user-images.githubusercontent.com/310049/46180859-33d23880-c299-11e8-905d-92353cc6ed73.jpg)

**Comment by beraldoleal** [comment]
![screen shot 2018-11-06 at 13 49 55](https://user-images.githubusercontent.com/49336/48075654-e8317980-e1ca-11e8-902c-cdfbbb2526f7.png)

**Comment by valessiobrito** [comment]
@beraldoleal please inform your resolution and the browser please. I can not reproduce this way. 

My print using:  chrome and resizing browser.

![captura de tela de 2018-11-06 14-00-12](https://user-images.githubusercontent.com/310049/48076505-735f3f00-e1cc-11e8-869a-6c980a84c431.png)
![captura de tela de 2018-11-06 13-59-51](https://user-images.githubusercontent.com/310049/48076506-735f3f00-e1cc-11e8-946e-3584d7967a90.png)
