### ISSUE TITLE
Kytos version install from github is still on 2018.1rc1

### ISSUE THREAD

**Issue by rmotitsuki** [kytos/kytos#816]
Cloning the Kytos from Github and running the setup.py installs the version as 2018.1rc1

**Comment by hdiogenes** [comment]
@macartur, it looks like metadata was not updated during the release: https://github.com/kytos/kytos/blob/master/kytos/core/metadata.py#L5

I've updated the release procedure to include it the next time.

**Comment by hdiogenes** [comment]
It looks like it was fixed on the 2018.1 branch, but not on master: https://github.com/kytos/kytos/compare/master...2018.1

Did we miss a merge?

**Comment by beraldoleal** [comment]
@macartur ?

**Comment by hdiogenes** [comment]
Fixed on PR #821.
