### ISSUE TITLE
Document the current messages

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#82]
Today we have already a good number of messages that napps can listen. Lets document this.

**Comment by beraldoleal** [comment]
@macartur where are you documenting this ?

**Comment by beraldoleal** [comment]
This should be documented in two places:

 - On kyco-core-napps specific napp directory we can create a "events.rst" with a full documentation of all events generated by this napp;
- And we should also have a webpage (sphinx) with a list of all napps events;

Of course we should avoid duplicate text. Includes should be used;

**Comment by macartur** [comment]
I made a pull request #145  with listened events in a table.

**Comment by macartur** [comment]
@beraldoleal , How can I make the includes if the kyco-core-napps is another repository ? Should I make a git submodule from kyco-core-napps to kyco ?

**Comment by macartur** [comment]
This was closed when #145  was merged.
