### ISSUE TITLE
FileNotFoundError during NApps tutorial

### ISSUE THREAD

**Issue by jondef95** [kytos/kytos#826]
I'm working through the [NApps tutorial](https://tutorials.kytos.io/napps/create_your_napp/) and have run into an error when attempting to create my first NApp skeleton. Running Python3.6 on Ubuntu 18.04, but I also ran into the error on Ubuntu 16.04:

> (kytos) kytos@kytostest:~/kytos/tutorials$ kytos napps create

> --------------------------------------------------------------
> Welcome to the bootstrap process of your NApp.
> --------------------------------------------------------------
> In order to answer both the username and the napp name,
> You must follow this naming rules:
>  - name starts with a letter
>  - name contains only letters, numbers or underscores
>  - at least three characters
> --------------------------------------------------------------
> 
> Please, insert your NApps Server username: tutorial
> Please, insert your NApp name: helloworld
> Please, insert a brief description for your NApp [optional]: Hello World!
> Traceback (most recent call last):
>   File "/home/kytos/kytos/bin/kytos", line 43, in <module>
>     parse(argv)
>   File "/home/kytos/kytos/lib/python3.6/site-packages/kytos/cli/commands/napps/parser.py", line 51, in parse
>     call(sys.argv[2], args)
>   File "/home/kytos/kytos/lib/python3.6/site-packages/kytos/cli/commands/napps/parser.py", line 61, in call
>     func(args)
>   File "/home/kytos/kytos/lib/python3.6/site-packages/kytos/cli/commands/napps/api.py", line 87, in create
>     NAppsManager.create_napp()
>   File "/home/kytos/kytos/lib/python3.6/site-packages/kytos/utils/napps.py", line 415, in create_napp
>     templates = os.listdir(templates_path)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/kytos/kytos/etc/skel/kytos/napp-structure/username/napp'

My username is `kytos`, and my venv name is also `kytos`. Changes to those didn't seem to have any effect either. The `skel `directory is what breaks the file path; after installing kytos in the virtual environment and looking in the `kytos/etc/` directory, there is no `skel` directory.

**Comment by renanrodrigo** [comment]
Same behavior as kytos/kytos-utils#190

**Comment by beraldoleal** [comment]
Thanks @jondef95 and @renanrodrigo . We will take a look ASAP.

**Comment by macartur** [comment]
I made a PR to master. @renanrodrigo  and @jondef95 could test the master branch to see if the bug was fixed ?

**Comment by jondef95** [comment]
Installing using the `setup.py` file in current master. Followed the commands listed [on the tutorial page](https://tutorials.kytos.io/napps/create_your_napp/) and still received the same errors. 

> FileNotFoundError: [Errno 2] No such file or directory: '/home/username/kytos-environment/etc/skel/kytos/napp-structure/username/napp'

However, if I install the requirements listed in the [developer's tutorial ](https://docs.kytos.io/kytos/developer/setup_develop_environment/) with the following command:

> pip install -r requirements/dev.txt

Then I am able to successfully create a NApp.

**Comment by hdiogenes** [comment]
Closing this as it has been fixed for a few months, with the many modifications to the installation procedure and also with the updated developer instructions (also related: #922).
