### ISSUE TITLE
Enhance CSS for printing/exporting to PDF

### ISSUE THREAD

**Issue by hdiogenes** [kytos/kytos#831]
Print CSS needs a few minor fixes, like reducing padding for the h1/h2 headers and source code examples, and hiding the footer links.

**Comment by valessiobrito** [comment]
Finished.

https://github.com/kytos/sphinx-theme/commit/ceb2cb36d377d3cd7b509c2ece27a776c0d5c326

[Example](https://github.com/kytos/kytos/files/2531586/teste2.pdf)
