### ISSUE TITLE
Add meta-packages to documentation

### ISSUE THREAD

**Issue by josemauro** [kytos/kytos#860]

**Comment by hdiogenes** [comment]
This was implemented in kytos/kytos-utils#186, kytos/kytos-utils#188, #791 and #832, but no documentation for it has been written yet.

Basically what we need to do is to create a new "Meta-NApp" ou "Meta-Package" section in the Developer Guide, explaining what is a meta-napp (a napp that doesn't contain executable code, just installs and enables/disables a specific set of napps), how it can be created (`kytos napps create --meta`), and how it can be used (just like a normal napp: `kytos napps install/enable/disable META_NAPP_NAME`).

**Comment by beraldoleal** [comment]
@hdiogenes please can you build the new documentation on our server?

**Comment by hdiogenes** [comment]
Done! It's the final section on this page: https://docs.kytos.io/developer/creating_a_napp/
