### ISSUE TITLE
Create base posix unix daemon

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos#9]

**Comment by cemsbr** [comment]
@beraldoleal, I see this as a duplicate of #71. If I'm wrong, please, reopen this issue.

**Comment by beraldoleal** [comment]
@cemsbr no, this is a different one. This is the daemon itself.

Our kytosd script should behave like an unix posix daemon:

```
-d for start as daemon, otherwise start in foreground;
-c for read config files
-p specific a pid file
```

Also our logs should be redirected to console when in foreground and to syslog (or a specific log file) when running as daemon (in background).

And also signals.

https://www.python.org/dev/peps/pep-3143/

(Regarding the log stuff, we can do latter and open a different issue)

We have also to check if daemon lib supports python3.6. We disabled because of import error.

**Comment by beraldoleal** [comment]
At least we should have stop / start and daemon mode.

**Comment by abaruchi** [comment]
@cemsbr As far as I could understand the code, the `bin/kytosd` is responsible to call the start method of Controller class (which is defined in `kytos/core/controller`). 
According to pep-3143 we could do something like this:
```
import daemon

from spam import do_main_program

with daemon.DaemonContext():
    do_main_program()  <- run the start method here.
```
What do you think?
Of course, it would be just a temporary solution. pep-3143 has several features that we can use to perform stop/start and reload.

**Comment by beraldoleal** [comment]
@cemsbr do you have any update on this ?

**Comment by cemsbr** [comment]
Now, the default behavior is background mode unless "-f" or "--foregorund" is given. The "-c" option is dealt by KytosConfig. No PID management, but systemd does it automatically.

**Comment by beraldoleal** [comment]
Thanks. Since that we have more work to do here on this issue, I will move this to 2017.1b2

**Comment by beraldoleal** [comment]
Please check all references to other issues here (#103 and #34)

**Comment by beraldoleal** [comment]
Basic daemon is working, so I will close this, since that is a huge issue. Let's create one issue per feature on daemon.
