### ISSUE TITLE
Error running kytos from PyPI installation

### ISSUE THREAD

**Issue by gleybersonandrade** [kytos/kytos#904]
When I tried to run Kytos from Pypi installation, a dependencies error ocurred: _ModuleNotFoundError: No module named 'flask'_.

This error occur in 2019.1b2, and these are the steps to get this:

create an environment: _python3.6 -m venv env_
use the environment: _source env/bin/activate_
install base dependencies: _pip install --upgrade pip setuptools wheel_
install 2019.1b2 kytos release: _pip install --pre kytos_
run kytos in foreground: _kytosd -f_

**Comment by josemauro** [comment]
PR  #911 fixed this issue.
