### ISSUE TITLE
Create a default log format

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos#92]
It should be easy for devs to create a log for their apps so they are able to ignore other log messages and focus in their own messages. However, a new log (e.g. `logging.getLogger('My App')`) is not formatted as `logging.getLogger('KycoNApp')`. Besides, many threads of the main app class are created and there is no thread name in log.

**Comment by cemsbr** [comment]
I edited the first post and reopened the issue.

**Comment by beraldoleal** [comment]
We still need a better log handler. Please see #34
