### ISSUE TITLE
Update dependencies management to use pipenv

### ISSUE THREAD

**Issue by josemauro** [kytos/kytos#940]
Python Packaging User Guide recommends to use pipenv [1] to manage dependencies. Currently kytos use pip to install dependencies separating dev and production dependencies. That  separation must keep in with pipenv.

[1] https://packaging.python.org/tutorials/managing-dependencies/

**Comment by beraldoleal** [comment]
Related #494

**Comment by josemauro** [comment]
Pipenv showed up not to be a good tool to Kytos project once Kytos have multiple workflows and have a lib,  applications and sub-applications (napps). Pipenv at this moment doens't work very well with multiple workflows because it forces each one have a separeted virtualenv and besides that time to generate Pipfile.lock is too long (not very  atractive). For now, the current tools (pip, pip-compile and setuptools) it seems more suited for Kytos Project and it was decided to standardize dependences management to all repos in Kytos Project (issue #947).
