### ISSUE TITLE
Check if installing kytos using pip get the right version of kytos/ui 

### ISSUE THREAD

**Issue by josemauro** [kytos/kytos#991]
-Install kytos using pip
-Run UI
-Check if UI is using jquery 3.4.1 (updated in the last version of UI)

**Comment by hdiogenes** [comment]
If I remember right, it downloads the latest release from https://github.com/kytos/ui/releases. Maybe that's why it's not getting the latest version (release wasn't done).

**Comment by josemauro** [comment]
I just checked it.  It is giving 2.2.4 jQuery version. It should be giving 3.4.1.
![Screenshot from 2019-12-12 10-30-39](https://user-images.githubusercontent.com/18131211/70716154-8c3cfc80-1cca-11ea-8496-97487f38e966.png)

**Comment by hdiogenes** [comment]
Fixed with the new release of the Kytos UI. The Kytos release procedure was updated to include the steps necessary for this.
